<?php

namespace Domain\BannerBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Domain\BannerBundle\Entity\Banner;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    protected function getBannerQueryBuilder()
    {
        return $this->createQueryBuilder('b')
            ->where('b.isActive = true');
    }

    /**
     * @return QueryBuilder
     */
    protected function getBannerByTypeQueryBuilder()
    {
        return $this->getBannerQueryBuilder()
            ->join('b.type', 'bt');
    }

    /**
     * @param int $code
     *
     * @return Banner[]
     */
    public function getBannerByTypeCode(int $code)
    {
        return $this->getBannerByTypeQueryBuilder()
            ->andWhere('bt.code = :code')
            ->setParameter('code', $code)
            ->getQuery()
            ->getResult();
    }
}
