domain_article_homepage:
    path:     /
    defaults: { _controller: DomainArticleBundle:Article:index }

domain_article_view:
    path:     /article/{slug}
    defaults: { _controller: DomainArticleBundle:Article:view }

domain_article_category:
    path:     /category/{category}
    defaults: { _controller: DomainArticleBundle:Article:category }
