domain_article_homepage:
    path:     /
    defaults: { _controller: DomainArticleBundle:Article:index }
    options:
        sitemap:
            priority: 0.7
            changefreq: weekly
            section: article

domain_article_view:
    path:     /article/{slug}
    defaults: { _controller: DomainArticleBundle:Article:view }

domain_article_category:
    path:     /category/{categorySlug}
    defaults: { _controller: DomainArticleBundle:Article:category }
