services:
    domain_report.admin.subscription_report:
        class: Domain\ReportBundle\Admin\SubscriptionReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\SubscriptionReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Subscription Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:SubscriptionReport\list.html.twig']]

    domain_report.admin.category_report:
        class: Domain\ReportBundle\Admin\CategoryReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\CategoryReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:CategoryReport\list.html.twig']]

    domain_report.admin.keywords_report:
        class: Domain\ReportBundle\Admin\KeywordsReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\SearchLog, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Keywords Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:KeywordsReport\list.html.twig']]

    domain_report.admin.ad_usage_report:
        class: Domain\ReportBundle\Admin\AdUsageReportAdmin
        arguments: [~, Oxa\DfpBundle\Entity\DoubleClickLineItem, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Ad Usage Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:AdUsageReport\list.html.twig']]

    domain_report.admin.views_and_visitors_report:
        class: Domain\ReportBundle\Admin\ViewsAndVisitorsReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\Visitor, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Views & Visitors Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:ViewsAndVisitorsReport\list.html.twig']]

    domain_report.admin.interactions:
        class: Domain\ReportBundle\Admin\InteractionsReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\Interaction, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Interactions Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:InteractionsReport\list.html.twig']]