services:
    domain_report.admin.subscription_report:
        class: Domain\ReportBundle\Admin\SubscriptionReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\SubscriptionReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Subscription Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:SubscriptionReport\list.html.twig']]

    domain_report.admin.category_report:
        class: Domain\ReportBundle\Admin\CategoryReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\CategoryReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:CategoryReport\list.html.twig']]

    domain_report.admin.views_and_visitors_report:
        class: Domain\ReportBundle\Admin\ViewsAndVisitorsReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\ViewAndImpressionReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Views and Impressions Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:ViewsAndVisitorsReport\list.html.twig']]

    domain_report.admin.user_action_report:
        class: Domain\ReportBundle\Admin\UserActionReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\UserActionReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CMS History Log}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:UserActionReport\list.html.twig']]

    domain_report.admin.feedback_report:
        class: Domain\ReportBundle\Admin\FeedbackReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\UserActionReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Feedback}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:FeedbackReport\list.html.twig']]

    domain_report.admin.export_report:
        class: Domain\ReportBundle\Admin\ExportReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\ExportReport, DomainReportBundle:CRUDPostponeExport]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Export Reports}
