services:
    domain_report.admin.subscription_report:
        class: Domain\ReportBundle\Admin\SubscriptionReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\SubscriptionReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Subscription Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:SubscriptionReport\list.html.twig']]
    domain_report.admin.category_report:
        class: Domain\ReportBundle\Admin\CategoryReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\CategoryReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category Report}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:CategoryReport\list.html.twig']]
