services:
    domain_report.admin.subscription_report:
        class: Domain\ReportBundle\Admin\SubscriptionReportAdmin
        arguments: [~, Domain\ReportBundle\Entity\SubscriptionReport, DomainReportBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Subscription Reports}
        calls:
            - [ setTemplate, ['list', 'DomainReportBundle:Admin:SubscriptionReport\list.html.twig']]
    domain_report.manager.subscription_report_manager:
        class: Domain\ReportBundle\Manager\SubscriptionReportManager
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.exporter:
        class: Domain\ReportBundle\Service\Export\Exporter
        calls:
            - [ setContainer, [ '@service_container' ]]
    domain_report.exporter.subscription_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\SubscriptionPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@spraed.pdf.generator' ]]
            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
    domain_report.exporter.subscription_excel_exporter:
        class: Domain\ReportBundle\Service\Export\SubscriptionExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]
