services:
    # managers
    domain_report.manager.subscription_report_manager:
        class: Domain\ReportBundle\Manager\SubscriptionReportManager
        arguments:
            - '@mongodb.manager'
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.manager.geolocation_manager:
        class: Domain\ReportBundle\Manager\GeolocationManager
        arguments: [ '@mongodb.manager' ]
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.manager.business_overview_report_manager:
        class: Domain\ReportBundle\Manager\BusinessOverviewReportManager
        arguments:
            - '@domain_business.manager.business_profile'
            - '@domain_report.manager.category_overview_report_manager'
            - '@mongodb.manager'
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.manager.category_overview_report_manager:
        class: Domain\ReportBundle\Manager\CategoryOverviewReportManager
        arguments: ['@mongodb.manager']
        calls:
            - [ setContainer, [ '@service_container' ] ]

    domain_report.manager.keywords_report_manager:
        class: Domain\ReportBundle\Manager\KeywordsReportManager
        arguments: [ '@mongodb.manager' ]

    domain_report.manager.social_networks_report_manager:
        class: Domain\ReportBundle\Manager\SocialNetworksReportManager
        arguments: [ '@mongodb.manager' ]

    # export services
    domain_report.exporter:
        class: Domain\ReportBundle\Service\Export\Exporter
        calls:
            - [ setContainer, [ '@service_container' ]]
    domain_report.exporter.subscription_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\SubscriptionPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@knp_snappy.pdf' ]]
            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
    domain_report.exporter.subscription_excel_exporter:
        class: Domain\ReportBundle\Service\Export\SubscriptionExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]
    domain_report.exporter.category_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\CategoryPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@knp_snappy.pdf' ]]
            - [ setCategoryOverviewReportManager, [ '@domain_report.manager.category_overview_report_manager' ]]
    domain_report.exporter.category_excel_exporter:
        class: Domain\ReportBundle\Service\Export\CategoryExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setCategoryOverviewReportManager, [ '@domain_report.manager.category_overview_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]
    domain_report.exporter.business_overview_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\BusinessOverviewPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@knp_snappy.pdf' ]]
            - [ setViewsAndVisitorsReportManager, [ '@domain_report.manager.views_and_visitors' ]]
    domain_report.exporter.business_overview_excel_exporter:
        class: Domain\ReportBundle\Service\Export\BusinessOverviewExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setViewsAndVisitorsReportManager, [ '@domain_report.manager.views_and_visitors' ]]
            - [ setTranslator, [ '@translator.default' ]]

    domain_report.exporter.user_action_excel_exporter:
        class: Domain\ReportBundle\Service\Export\UserActionExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setUserActionReportManager, [ '@domain_report.manager.user_action_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]

    domain_report.google_analytics.data_fetcher:
        class: Domain\ReportBundle\Google\Analytics\DataFetcher
        parent: happyr.google_analytics.data_fetcher
        calls:
            - [ setClientProvider, [ '@domain_report.google_analytics.client_provider' ]]

    domain_report.google_analytics.client_provider:
        class: Domain\ReportBundle\Google\Analytics\ClientProvider
        arguments: ['analytics@infopaginas-142911.iam.gserviceaccount.com', %kernel.root_dir%/config/key.p12]

    domain_report.manager.ad_usage:
        class: Domain\ReportBundle\Manager\AdUsageReportManager
        arguments: [ '@mongodb.manager' ]
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.manager.views_and_visitors:
        class: Domain\ReportBundle\Manager\ViewsAndVisitorsReportManager
        arguments: [ '@domain_report.manager.business_overview_report_manager' ]

    domain_report.ads_exporter.excel:
        class: Domain\ReportBundle\Service\Export\BusinessAdsReportExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setBusinessOverviewReportManager, [ '@domain_report.manager.business_overview_report_manager' ]]
            - [ setAdUsageReportManager, [ '@domain_report.manager.ad_usage' ]]
            - [ setTranslator, [ '@translator.default' ]]

    domain_report.interaction_exporter.excel:
        class: Domain\ReportBundle\Service\Export\BusinessInteractionReportExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setBusinessOverviewReportManager, [ '@domain_report.manager.business_overview_report_manager' ]]
            - [ setKeywordsReportManager, [ '@domain_report.manager.keywords_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]

    domain_report.ads_exporter.pdf:
        class: Domain\ReportBundle\Service\Export\BusinessAdsReportPdfExporter
        calls:
            - [ setBusinessOverviewReportManager, [ '@domain_report.manager.business_overview_report_manager' ]]
            - [ setAdUsageReportManager, [ '@domain_report.manager.ad_usage' ]]
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@knp_snappy.pdf' ]]

    domain_report.interaction_exporter.pdf:
        class: Domain\ReportBundle\Service\Export\BusinessInteractionReportPdfExporter
        calls:
            - [ setBusinessOverviewReportManager, [ '@domain_report.manager.business_overview_report_manager' ]]
            - [ setKeywordsReportManager, [ '@domain_report.manager.keywords_report_manager' ]]
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@knp_snappy.pdf' ]]

    domain_report.charts_exporter.pdf:
        class: Domain\ReportBundle\Service\Export\BusinessChartReportPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@knp_snappy.pdf' ]]

    domain_report.manager.business_report_api_manager:
            class: Domain\ReportBundle\Manager\BusinessReportApiManager
            arguments: [ '@service_container' ]

    domain_report.manager.user_action_report_manager:
        class: Domain\ReportBundle\Manager\UserActionReportManager
        arguments:
            - '@security.token_storage'
            - '@mongodb.manager'

    domain_report.manager.feedback_report_manager:
        class: Domain\ReportBundle\Manager\FeedbackReportManager
        arguments:
            - '@mongodb.manager'
            - '@domain_site.mailer'

    domain_report.manager.postpone_export_report:
        class: Domain\ReportBundle\Manager\PostponeExportReportManager
        arguments:
            - '@service_container'

    domain_report.exporter.business_profile_excel_exporter:
        class: Domain\ReportBundle\Service\Export\BusinessProfileExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setBusinessProfileManager, [ '@domain_business.manager.business_profile' ]]
            - [ setTranslator, [ '@translator.default' ]]

    domain_report.exporter.user_action_csv_exporter:
        class: Domain\ReportBundle\Service\Export\UserActionCsvExporter
        calls:
            - [ setUserActionReportManager, [ '@domain_report.manager.user_action_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]

    domain_report.exporter.business_profile_csv_exporter:
        class: Domain\ReportBundle\Service\Export\BusinessProfileCsvExporter
        calls:
            - [ setBusinessProfileManager, [ '@domain_business.manager.business_profile' ]]
            - [ setTranslator, [ '@translator.default' ]]

    domain_report.exporter.feedback_report_csv_exporter:
        class: Domain\ReportBundle\Service\Export\FeedbackReportCsvExporter
        calls:
            - [ setFeedbackReportManager, [ '@domain_report.manager.feedback_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]