services:
    domain_report.manager.subscription_report_manager:
        class: Domain\ReportBundle\Manager\SubscriptionReportManager
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.manager.category_report_manager:
        class: Domain\ReportBundle\Manager\CategoryReportManager
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.exporter:
        class: Domain\ReportBundle\Service\Export\Exporter
        calls:
            - [ setContainer, [ '@service_container' ]]
    domain_report.exporter.subscription_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\SubscriptionPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@spraed.pdf.generator' ]]
            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
    domain_report.exporter.subscription_excel_exporter:
        class: Domain\ReportBundle\Service\Export\SubscriptionExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]
    domain_report.exporter.category_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\CategoryPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@spraed.pdf.generator' ]]
            - [ setCategoryReportManager, [ '@domain_report.manager.category_report_manager' ]]
#    domain_report.exporter.subscription_excel_exporter:
#        class: Domain\ReportBundle\Service\Export\SubscriptionExcelExporter
#        calls:
#            - [ setPhpExcel, [ '@phpexcel' ]]
#            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
#            - [ setTranslator, [ '@translator.default' ]]
