services:
    # managers
    domain_report.manager.subscription_report_manager:
        class: Domain\ReportBundle\Manager\SubscriptionReportManager
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.manager.category_report_manager:
        class: Domain\ReportBundle\Manager\CategoryReportManager
        calls:
            - [ setContainer, [ '@service_container' ] ]
    domain_report.manager.business_overview_report_manager:
        class: Domain\ReportBundle\Manager\BusinessOverviewReportManager
        calls:
            - [ setContainer, [ '@service_container' ] ]

    # export services
    domain_report.exporter:
        class: Domain\ReportBundle\Service\Export\Exporter
        calls:
            - [ setContainer, [ '@service_container' ]]
    domain_report.exporter.subscription_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\SubscriptionPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@spraed.pdf.generator' ]]
            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
    domain_report.exporter.subscription_excel_exporter:
        class: Domain\ReportBundle\Service\Export\SubscriptionExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setSubscriptionReportManager, [ '@domain_report.manager.subscription_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]
    domain_report.exporter.category_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\CategoryPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@spraed.pdf.generator' ]]
            - [ setCategoryReportManager, [ '@domain_report.manager.category_report_manager' ]]
    domain_report.exporter.category_excel_exporter:
        class: Domain\ReportBundle\Service\Export\CategoryExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setCategoryReportManager, [ '@domain_report.manager.category_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]
    domain_report.exporter.business_overview_pdf_exporter:
        class: Domain\ReportBundle\Service\Export\BusinessOverviewPdfExporter
        calls:
            - [ setTemplateEngine, [ '@templating' ]]
            - [ setPdfGenerator, [ '@spraed.pdf.generator' ]]
            - [ setBusinessOverviewReportManager, [ '@domain_report.manager.business_overview_report_manager' ]]
    domain_report.exporter.business_overview_excel_exporter:
        class: Domain\ReportBundle\Service\Export\BusinessOverviewExcelExporter
        calls:
            - [ setPhpExcel, [ '@phpexcel' ]]
            - [ setBusinessOverviewReportManager, [ '@domain_report.manager.business_overview_report_manager' ]]
            - [ setTranslator, [ '@translator.default' ]]

    domain_report.google_analytics.data_fetcher:
        class: Domain\ReportBundle\Google\Analytics\DataFetcher
        parent: happyr.google_analytics.data_fetcher
