domain_site_geolocation_autocomplete:
    path:   /autocomplete
    defaults: { _controller: DomainSiteBundle:Geolocation:autocomplete }
    options:
        sitemap:
            priority: 0.7
            changefreq: weekly
            section: main

