domain_site_home_index:
    path:     /
    defaults: { _controller: DomainSiteBundle:Home:index }
    options:
        expose: true
        sitemap:
            priority: 1
            section: main
