domain_site_user_profile:
    path:     /profile
    defaults: { _controller: DomainSiteBundle:User:profile }
    options:
        expose: true

domain_site_user_profile_save:
    path:     /profile/save
    defaults: { _controller: DomainSiteBundle:User:saveProfile }
    options:
        expose: true

domain_site_user_password_update:
    path:     /password/update
    defaults: { _controller: DomainSiteBundle:User:passwordUpdate }
    options:
        expose: true

domain_site_user_profile_upgrade:
    path:     /profile/upgrade
    defaults: { _controller: DomainSiteBundle:User:processUpgrade }
    options:
        expose: true