services:
    domain_menu.admin.menu:
        class: Domain\MenuBundle\Admin\MenuAdmin
        arguments: [~, Domain\MenuBundle\Entity\Menu, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Site Menu}
