services:
    domain_banner.admin.banner:
        class: Domain\BannerBundle\Admin\BannerAdmin
        arguments: [~, Domain\BannerBundle\Entity\Banner, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Banners}
