parameters:
    google_auth_ini_path: 'src/Oxa/DfpBundle/Resources/config/google/adsapi_php.ini'

services:
    oxa_dpf.google.auth:
        class: Oxa\DfpBundle\Manager\AuthManager
        arguments:
            - '%google_auth_ini_path%'

    oxa_dfp.manager:
        class: Oxa\DfpBundle\Manager\DfpManager
        calls:
            - [ setAuthManager, [ '@oxa_dpf.google.auth' ]]
            - [ setOrderReportManager, [ '@oxa_dfp.manager.order_report' ]]
            - [ setAdUsageReportManager, [ '@domain_report.manager.ad_usage' ]]

    oxa_dfp.manager.order_report:
        class: Oxa\DfpBundle\Manager\OrderReportManager
