parameters:
    google_auth_ini_path:      "@@OxaDfpBundle/Resources/config/google/auth.ini"
    google_settings_ini_path:  "@@OxaDfpBundle/Resources/config/google/settings.ini"
    api_properties_path:       "@@OxaDfpBundle/Resources/config/google/api.properties"

services:
    oxa_dfp.google.user:
        class: Oxa\DfpBundle\Google\Api\Ads\Dfp\Lib\DfpUser
        arguments:
            - "%google_auth_ini_path%"
            - null
            - null
            - "%google_settings_ini_path%"
            - null
            - "%api_properties_path%"
            - "@service_container"

    oxa_dfp.service.report:
        class: Oxa\DfpBundle\Service\Google\ReportService
        arguments: ['@oxa_dfp.google.user']

    oxa_dfp.service.order:
        class: Oxa\DfpBundle\Service\Google\OrderService
        arguments: ['@oxa_dfp.google.user']

    oxa_dfp.service.company:
        class: Oxa\DfpBundle\Service\Google\CompanyService
        arguments: ['@oxa_dfp.google.user']

    oxa_dfp.service.line_item:
        class: Oxa\DfpBundle\Service\Google\LineItemService
        arguments: ['@oxa_dfp.google.user']

    oxa_dfp.manager:
        class: Oxa\DfpBundle\Manager\DfpManager
        arguments: ['@oxa_dfp.service.report']