<?php

namespace Domain\BusinessBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getAvailableAreasQb() : QueryBuilder
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.isActive = TRUE');

        return $qb;
    }
}
