<?php

namespace Domain\BusinessBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailableBrandsQb()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->where('b.isActive = TRUE');

        return $qb;
    }
}
