<?php

namespace Domain\BusinessBundle\Repository;

/**
 * BusinessProfilePhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessProfilePhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
