<?php

namespace Domain\BusinessBundle\Repository;

use Domain\BusinessBundle\Entity\BusinessProfile;
use FOS\UserBundle\Model\UserInterface;

/**
 * BusinessReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessReviewRepository extends \Doctrine\ORM\EntityRepository
{
    const SLUG = 'DomainBusinessBundle:Review\BusinessReview';

    /**
     * @param UserInterface $user
     * @return array
     */
    public function findUserReviews(UserInterface $user)
    {
        $reviews = $this->findBy([
            'user' => $user,
            'isActive' => true,
        ]);

        return $reviews;
    }

    /**
     * @param BusinessProfile $businessProfile
     * @return null|object
     */
    public function findBusinessProfileLastReview(BusinessProfile $businessProfile)
    {
        $criteria = ['businessProfile' => $businessProfile];
        $order    = ['id' => 'DESC'];

        return $this->findOneBy($criteria, $order);
    }
}
