<?php

namespace Domain\BusinessBundle\Repository;

/**
 * BusinessReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
