<?php

namespace Domain\BusinessBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailableCategoriesQb()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.isActive = TRUE');

        return $qb;
    }
}
