<?php

namespace Domain\BusinessBundle\Repository;

/**
 * ChangeSetEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeSetEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
