<?php

namespace Domain\BusinessBundle\Repository;

/**
 * ChangeSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeSetRepository extends \Doctrine\ORM\EntityRepository
{
}
