<?php

namespace Domain\BusinessBundle\Repository;

use Domain\BusinessBundle\Entity\Address\Country;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getCountriesShortNames()
    {
        $countries = $this->createQueryBuilder('c')
            ->select(['c.shortName', 'c.name'])
            ->getQuery()
            ->getResult();

        $result = [];
        foreach ($countries as $country) {
            $result[$country['shortName']] = $country['name'];
        }

        return $result;
    }

    public function getAvailableCountriesQb()
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->where('c.isActive = TRUE')
            ->orderBy('c.name')
        ;

        return $qb;
    }
}
