<?php

namespace Domain\BusinessBundle\Repository;

use Domain\BusinessBundle\Entity\Address\Country;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getCountriesShortNames()
    {
        $countries = $this->createQueryBuilder('c')
            ->select(['c.shortName', 'c.name'])
            ->getQuery()
            ->getResult();

        $result = [];
        foreach ($countries as $country) {
            $result[$country['shortName']] = $country['name'];
        }

        return $result;
    }

    public function getAvailableCountriesQb()
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->where('c.isActive = TRUE')
            ->addSelect('CASE WHEN c.shortName = :defaultCountry THEN 1 ELSE 0 END AS HIDDEN sortCondition')
            ->addOrderBy('sortCondition', 'DESC')
            ->addOrderBy('c.name')
            ->setParameter('defaultCountry', strtoupper(Country::PUERTO_RICO_SHORT_NAME))
        ;

        return $qb;
    }
}
