<?php

namespace Domain\BusinessBundle\Repository;

/**
 * DraftBusinessProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DraftBusinessProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
