<?php

namespace Domain\BusinessBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getAvailablePaymentMethodsQb()
    {
        $qb = $this->createQueryBuilder('pm');
        $qb->where('pm.isActive = TRUE');

        return $qb;
    }
}
