<?php

namespace Domain\BusinessBundle\Repository;

/**
 * ReviewTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
