<?php

namespace Domain\BusinessBundle\Repository;

/**
 * SubscriptionPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
