<?php

namespace Domain\BusinessBundle\Repository;

use Domain\BusinessBundle\Entity\BusinessProfile;
use Domain\BusinessBundle\Entity\Subscription;
use Domain\BusinessBundle\Util\Traits\StatusTrait;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param BusinessProfile $businessProfile
     *
     * @return Subscription[]
     */
    public function getActualSubscriptionsForBusiness(BusinessProfile $businessProfile)
    {
        $queryBuilder = $this->createQueryBuilder('sub');

        $queryBuilder->select('s')
            ->from('DomainBusinessBundle:Subscription', 's')
            ->andWhere('s.businessProfile = :businessProfile')
            ->andWhere('s.status IN (:actualSubscriptions)')
            ->setParameter('businessProfile', $businessProfile)
            ->setParameter('actualSubscriptions', StatusTrait::getActualStatuses())
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
