<?php

namespace Domain\BusinessBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getAvailableTagsQb()
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where('t.isActive = TRUE');

        return $qb;
    }
}
