imports:
    - { resource: config.yml }
parameters:
    domain: 'localhost'
    amazon_aws_key:         AKIAJNXO2HSEBOJIFU7A
    amazon_aws_secret_key:  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
    amazon_s3_base_url:     infopaginas-dev.s3-website-us-east-1.amazonaws.com
    amazon_s3_bucket_name:  infopaginas-dev

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels:
        ['foo']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        glogen:
            type: stream
            path: "%kernel.logs_dir%/glogen.log"
            level: debug
            channels: 'foo'
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

