imports:
    - { resource: config.yml }
parameters:
    domain: 'infopaginas-stage.oxagile.com'

    google_youtube_api_client_key: '1038987589554-5beh6k655b6nma7ltrd9sv17avbobjkp.apps.googleusercontent.com'
    google_youtube_secret_key: 'MqwCsstQtzNrT_WTgWW5Styc'

#    youtube user Infopaginaspr
    google_youtube_channel_id: 'UCWWRfV9jE0GoEgfGEc6QWVQ'

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

google:
    analytics:
        enhanced_ecommerce: true
        session_auto_started: true
        trackers:
            default:
                name: MyJavaScriptCompatibleVariableNameWithNoSpaces
                accountId: UA-10361727-2
                domain: www.infopaginas.com
                setSiteSpeedSampleRate: 5
                allowAnchor: true
                allowHash: true
                includeNamePrefix: false
                plugins:
                    - 'linkid'
                    - 'ec'
        whitelist: [ 'q', 'utm_source', 'utm_medium', 'utm_term', 'utm_content', 'utm_campaign' ]

happyr_google_site_authenticator:
    cache_service: 'cache.provider.my_file_system'
    tokens:
        google_analytics:
            client_id: '496444845522-no82atjdrcmbnbo2jl6238g28qiamae9.apps.googleusercontent.com'
            client_secret: 'eRZEJiZIQw9w0SKyye-68jTU'
            redirect_url: 'https://infopaginas-prod.com/admin/authenticate-google/return-url'
            scopes: ['https://www.googleapis.com/auth/analytics.readonly']

happyr_google_analytics:
    http_client: 'httplug.client'
    http_message_factory: 'httplug.message_factory'
    tracking_id: UA-10361727-2
    fetching:
        client_service: 'google.client.google_analytics'
        view_id: 20865077
        cache_service: 'cache.provider.my_file_system'
        cache_lifetime: 3600

twig:
    globals:
        google_tag_manager_id:    'GTM-TWPMVZ'
