imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: extra-configs/sonata_admin.yml }
    - { resource: extra-configs/user.yml }
    - { resource: extra-configs/editor.yml }
    - { resource: extra-configs/extensions.yml }
    - { resource: extra-configs/sonata_media.yml }
    - { resource: extra-configs/sonata_translation.yml }
    - { resource: "@DomainMenuBundle/Resources/config/services.yml" }
    - { resource: "@DomainArticleBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    locales: [en, es]
    route_locales: en|es

framework:
    #esi:             ~
    translator:      { fallbacks: %locales% }
    default_locale:  "%locale%"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'OxaSonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
    form_themes:
        - 'DomainBusinessBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    enum: string
        types:
            json: Sonata\Doctrine\Types\JsonType
            TaskType: Domain\BusinessBundle\DBAL\Types\TaskType
            TaskStatusType: Domain\BusinessBundle\DBAL\Types\TaskStatusType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            OxaSonataUserBundle: ~
            SonataUserBundle: ~
            FOSUserBundle: ~
            OxaSonataMediaBundle: ~
            SonataMediaBundle: ~
            SonataMediaBundle: ~
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable
                is_bundle: false
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

ivory_google_map:
    geocoder:
        enabled: true
        class: "Ivory\GoogleMap\Services\Geocoding\Geocoder"
        provider:
            class: "Ivory\GoogleMap\Services\Geocoding\GeocoderProvider"
        adapter: "Geocoder\HttpAdapter\CurlHttpAdapter"
