imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: extra-configs/sonata_admin.yml }
    - { resource: extra-configs/user.yml }
    - { resource: extra-configs/editor.yml }
    - { resource: extra-configs/extensions.yml }
    - { resource: extra-configs/sonata_media.yml }
    - { resource: extra-configs/sonata_translation.yml }
    - { resource: extra-configs/twig_constant.yml }
    - { resource: extra-configs/assetic.yml }
    - { resource: extra-configs/db_slaves.yml, ignore_errors: true }
    - { resource: "@OxaSonataUserBundle/Resources/config/services.yml" }
    - { resource: "@DomainArticleBundle/Resources/config/services.yml" }
    - { resource: "@JMaitanSonataMediaCropBundle/Resources/config/services.xml" }
    - { resource: "@OxaGeolocationBundle/Resources/config/services.yml" }
    - { resource: "@OxaDfpBundle/Resources/config/services.yml" }
    - { resource: "@ElasticSearchBundle/Resources/config/services.yml" }
    - { resource: "@MongoDbBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app_version: '1.8.0'
    locale: en
    locales: [en, es]
    locale_data:
        es:
            domain: ''
            title: 'Espa&ntilde;ol'
        en:
            domain: 'en'
            title: 'English'
    route_locales: en|es
    locale_admin:
        url_part: 'admin'
        locale: 'en'
    videos_upload_path: %assetic.write_to%/uploads/videos
    default_image:
        path: '/assets/images/'
        business_image: 'header-logo.png'
        article:
            image: 'header-logo.png'
            width: '221'
            height: '42'
    google_map_api_key: "AIzaSyD-1F1-Wr4GLyP5Pk2-IH4DAd_jW0w4xqU"
    google_map_default_center: '18.446344, -66.07558'
    google_map_default_center_name: 'San Juan'
    google_map_default_zoom: 8
    google_map_min_single_zoom: 15  #min zoom for single map marker
    google_tag_manager_id: 'GTM-TWPMVZ'
    google_analytics_id:   'UA-10361727-2'
    seo_custom_settings:
        company_name: 'Infopáginas'
        title_max_length: 60
        title_category_max_length: 20
        business_name_length: 45    # + 3 sign
        locality_length: 15         # + 3 sign
        brand_length: 12
        description_max_length: 160
        description_category_max_length: 120    # for all categories
        description_category_separator: ', '
        description_category_cut: '...'
        default_article_author: 'Infopáginas Media'
    video_download_path: '/../web/uploads/videos/'
    export_report_path: '/../web/uploads/export/'
    breadcrumb_max_length: 38
    google_youtube_api_client_key:  '257125561113-k1b051ctf2uvgii4um1v5intdj7habeg.apps.googleusercontent.com'
    google_youtube_secret_key:      '5BFK_k2oVD7Uh-Gn85LrHYcC'
    google_youtube_privacy: '%google_youtube_video_privacy%'
    google_youtube_channel_id: '%google_youtube_user_channel_id%'
    google_badge_partner_id: '6032772200'
    validators:
        keyword:
            one_word: '/^[a-zA-Z0-9àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸçÇßØøÅåÆæœ]*$/'

framework:
    #esi:             ~
    translator:      { fallbacks: %locales% }
    default_locale:  "%locale%"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enabled: true
        enable_annotations: true
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        storage_id: dynamicDomainSessionStorage
        name: SFSESSID
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'OxaSonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
    form_themes:
        - 'DomainBusinessBundle:Form:fields.html.twig'
    globals:
        app_version: '%app_version%'
        google_badge_partner_id: '%google_badge_partner_id%'
        google_map_api_key: '%google_map_api_key%'
        google_map_default_center: '%google_map_default_center%'
        google_map_default_zoom: '%google_map_default_zoom%'
        google_map_min_zoom: '%google_map_min_single_zoom%'
        media_file_name_max_length: 20
        breadcrumb_max_length: '%breadcrumb_max_length%'
        keyword_max_length: 50

#       todo confirm date formats
        review_date_format:        'd M Y H:i'
        article_date_format:       'M d, Y'
        business_date_format:      'Y-m-d'
        subscription_date_format:  'Y-m-d'
        category_report_date_format: 'm/d/Y'
        report_generated_datetime_format: 'm/d/Y H:i:s'
        monthly_report_date_format: 'F, Y'
        ads_stat_date_format:      'd.m.Y'
        task_date_format:          'd M, Y, H:i:s A'
        working_hours_date_format: 'g:i A'
        emergency_update_date_format: 'd F Y, g:ia'
        google_tag_manager_id:     '%google_tag_manager_id%'
        google_analytics_id:       '%google_analytics_id%'
        default_country:           'pr'
        defaultLocale: '%locale%'

#       validation patterns
        validators: '%validators%'
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    enum: string
        types:
            json: Sonata\Doctrine\Types\JsonType
            TaskType: Domain\BusinessBundle\DBAL\Types\TaskType
            TaskStatusType: Domain\BusinessBundle\DBAL\Types\TaskStatusType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            OxaSonataUserBundle: ~
            SonataUserBundle: ~
            FOSUserBundle: ~
            OxaSonataMediaBundle: ~
            SonataMediaBundle: ~
            SonataClassificationBundle: ~
            ApplicationSonataClassificationBundle: ~

#sonataClassificationBundle
sonata_classification:
    class:
        media: Oxa\Sonata\MediaBundle\Entity\Media

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

ivory_google_map:
    geocoder:
        enabled: true
        class: "Ivory\GoogleMap\Services\Geocoding\Geocoder"
        provider:
            class: "Ivory\GoogleMap\Services\Geocoding\GeocoderProvider"
        adapter: "Geocoder\HttpAdapter\CurlHttpAdapter"

hwi_oauth:
    http_client:
        timeout: 10
    connect:
        account_connector: oxa.user.oauth_provider
        confirmation: false
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           395706097433162
            client_secret:       a3b0120497f463012ea5b431e815a717
            scope:         "email"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email,first_name,last_name"
            paths:
                email:          email
        google:
            type:                google
            client_id:           '257125561113-k1b051ctf2uvgii4um1v5intdj7habeg.apps.googleusercontent.com'
            client_secret:       '5BFK_k2oVD7Uh-Gn85LrHYcC'
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

fos_js_routing:
    routes_to_expose: [ fos_user_security_check ]

google:
    analytics:
        enhanced_ecommerce: true
        session_auto_started: true
        trackers:
            default:
                name: MyJavaScriptCompatibleVariableNameWithNoSpaces
                accountId: UA-83876369-2
                domain: infopaginas.io
                setSiteSpeedSampleRate: 5
                allowAnchor: true
                allowHash: true
                includeNamePrefix: false
                plugins:
                    - 'linkid'
                    - 'ec'
        whitelist: [ 'q', 'utm_source', 'utm_medium', 'utm_term', 'utm_content', 'utm_campaign' ]

happyr_google_site_authenticator:
    cache_service: 'cache.provider.my_file_system'
    tokens:
        google_analytics:
            client_id: '496444845522-no82atjdrcmbnbo2jl6238g28qiamae9.apps.googleusercontent.com'
            client_secret: 'eRZEJiZIQw9w0SKyye-68jTU'
            redirect_url: 'http://infopaginas.io/app_dev.php/admin/authenticate-google/return-url'
            scopes: ['https://www.googleapis.com/auth/analytics.readonly']

oneup_flysystem:
    adapters:
        my_adapter:
            local:
                directory: %kernel.root_dir%/cache
    filesystems:
        local:
            adapter: my_adapter

cache_adapter:
  providers:
      my_file_system:
          factory: 'cache.factory.filesystem'
          options:
              flysystem_service: 'oneup_flysystem.local_filesystem'

happyr_google_analytics:
    http_client: 'httplug.client'
    http_message_factory: 'httplug.message_factory'
    tracking_id: UA-83876369-2
    fetching:
        client_service: 'google.client.google_analytics'
        view_id: 129461101
        cache_service: 'cache.provider.my_file_system'
        cache_lifetime: 3600

presta_sitemap:
    timetolive: 86400
    items_by_set: 50000

knp_gaufrette:
    adapters:
        video_storage:
            aws_s3:
                service_id:     aws.s3
                bucket_name:    %amazon_aws_bucket_name%
                options:
                    create:     true
                    directory:  '%amazon_aws_video_directory%'
        report_storage:
            aws_s3:
                service_id:     aws.s3
                bucket_name:    %amazon_aws_bucket_name%
                options:
                    create:     true
                    directory:  '%amazon_aws_report_directory%'
    filesystems:
        ipgn:
            adapter:    video_storage
            alias:      video_storage_filesystem
        export:
            adapter:    report_storage
            alias:      report_storage_filesystem

dubture_f_fmpeg:
    ffmpeg_binary: /usr/bin/ffmpeg
    ffprobe_binary: /usr/bin/ffprobe
    binary_timeout: 300 # Use 0 for infinite
    threads_count: 1

aws:
    version:    '2006-03-01'
    region:     '%amazon_aws_region%'
    credentials:
        key:    '%amazon_aws_key%'
        secret: '%amazon_aws_secret_key%'
    S3:
        version:    '2006-03-01'

elastic_search:
    host: '%elastic_search.host%'
    document_index: '%elastic_search.document_index%'
    indexing_page: 100

mongo_db:
    host: '%mongodb.host%'
    db:   '%mongodb.db%'
