imports:
    - { resource: config.yml }
parameters:
    domain: 'localhost'

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        cloudwatch:
            type: service
            level: debug
            channels: [!event]
            id: "app.monolog.handler.cloudwatch"
        console:
            type:   console
            channels: [!event, !doctrine]
        doctrine:
            action_level: debug
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_doctrine.log"
            channels: doctrine
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

