domain_emergency:
    resource: "@DomainEmergencyBundle/Resources/config/routing.yml"
    prefix:   /

jmaitan_media:
    resource: "@JMaitanSonataMediaCropBundle/Resources/config/routing.xml"
    prefix:   /jmaitan_media

oxa_wistia:
    resource: "@OxaVideoBundle/Resources/config/routing.yml"
    prefix:   /

domain_article:
    resource: "@DomainArticleBundle/Resources/config/routing.yml"
    prefix:   /articles

domain_page:
    resource: "@DomainPageBundle/Resources/config/routing.yml"
    prefix:   /

domain_business:
    resource: "@DomainBusinessBundle/Resources/config/routing.yml"
    prefix:   /

oxa_config:
    resource: "@OxaConfigBundle/Resources/config/routing.yml"
    prefix:   /config

domain_site:
    resource: "@DomainSiteBundle/Resources/config/routing.yml"
    prefix:   /

domain_search:
    resource: "@DomainSearchBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

sonata_user_resetting:
    resource: '@OxaSonataUserBundle/Resources/config/sonata_resetting_1.xml'
    prefix: /resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_resetting_reset:
    path:     /password_reset/{token}
    defaults: { _controller: DomainSiteBundle:Home:index }

fos_user_forgotten_password:
    path:     /forgotten_password
    defaults: { _controller: DomainSiteBundle:Home:index }

happyr_google_site_authenticator:
    resource: "@HappyrGoogleSiteAuthenticatorBundle/Resources/config/routing.yml"
    prefix:   /admin

oxa_youtube:
    resource: "@OxaVideoBundle/Resources/config/routing.yml"
    prefix:   /youtube/oauth/
