security:
    role_hierarchy:

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_SOFT_DELETE

        ROLE_SOFT_DELETE:
            - ROLE_PHYSICAL_DELETE_ABLE
            - ROLE_RESTORE_ABLE

        ROLE_ADMIN:
            - ROLE_SONATA_ADMIN

        # project role
        ROLE_ADMINISTRATOR:
            - ROLE_ADMIN
            - ROLE_SOFT_DELETE
            - ROLE_BUNDLES_ALL

        # project role
        ROLE_CONTENT_MANAGER:
            - ROLE_ADMIN
            - ROLE_BUNDLES_ALL

        # project role
        ROLE_SALES_MANAGER:
            - ROLE_ADMIN
            - ROLE_BUNDLES_ALL

        # project role
        ROLE_MERCHANT:

        # project role
        ROLE_CONSUMER:

        ROLE_BUNDLES_ALL:
            - ROLE_SONATA_USER_ADMIN_USER
            - ROLE_SONATA_USER_ADMIN_GROUP
            - ROLE_SONATA_USER_ADMIN_MEDIA


        ROLE_SONATA_USER_ADMIN_USER:
            - ROLE_SONATA_USER_ADMIN_USER_EDIT
            - ROLE_SONATA_USER_ADMIN_USER_LIST
            - ROLE_SONATA_USER_ADMIN_USER_CREATE
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
            - ROLE_SONATA_USER_ADMIN_USER_DELETE
            - ROLE_SONATA_USER_ADMIN_USER_EXPORT
            - ROLE_SONATA_USER_ADMIN_USER_OPERATOR
            - ROLE_SONATA_USER_ADMIN_USER_MASTER
        ROLE_SONATA_USER_ADMIN_GROUP:
            - ROLE_SONATA_USER_ADMIN_GROUP_EDIT
            - ROLE_SONATA_USER_ADMIN_GROUP_LIST
            - ROLE_SONATA_USER_ADMIN_GROUP_CREATE
            - ROLE_SONATA_USER_ADMIN_GROUP_VIEW
            - ROLE_SONATA_USER_ADMIN_GROUP_DELETE
            - ROLE_SONATA_USER_ADMIN_GROUP_EXPORT
            - ROLE_SONATA_USER_ADMIN_GROUP_OPERATOR
            - ROLE_SONATA_USER_ADMIN_GROUP_MASTER
        ROLE_SONATA_USER_ADMIN_MEDIA:
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_LIST
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_DELETE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_EXPORT
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_OPERATOR
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_MASTER
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_LIST
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_DELETE
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_EXPORT
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_OPERATOR
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_MASTER
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_LIST
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_DELETE
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_EXPORT
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_OPERATOR
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_MASTER