services:
    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    oxa.listener.user_crud_action:
        class: Oxa\Sonata\AdminBundle\EventListener\UserCRUDActionListener
        arguments: [@security.token_storage]
        tags:
            - {name: doctrine.event_listener, event: onFlush, priority: 1}

    oxa.sonata.manager.admin_manager:
        class: Oxa\Sonata\AdminBundle\Manager\AdminManager
        calls:
            - [ setContainer, [ '@service_container' ] ]

    oxa.sonata.twig.admin_extension:
        class: Oxa\Sonata\AdminBundle\Twig\AdminExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: admin_extension}

    oxa.sonata.admin.filter.type.insensitive_string:
        class: Oxa\Sonata\AdminBundle\Filter\CaseInsensitiveStringFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_string }

    oxa.sonata.admin.filter.type.datetime_range_expanded:
        class: Oxa\Sonata\AdminBundle\Filter\DateTimeRangeFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_datetime_range }

    oxa.sonata.admin.filter.type.date_expanded:
        class: Oxa\Sonata\AdminBundle\Filter\DateFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_date }

    oxa.sonata.admin.filter.type.date_range_expanded:
        class: Oxa\Sonata\AdminBundle\Filter\DateRangeFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_date_range }

    oxa.sonata.admin.filter.type.datetime_expanded:
        class: Oxa\Sonata\AdminBundle\Filter\DateTimeFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_datetime }

    oxa.sonata.admin.filter.type.time_expanded:
        class: Oxa\Sonata\AdminBundle\Filter\TimeFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_time }

    oxa.sonata.admin.form.type.model_autocomplete:
            class: Oxa\Sonata\AdminBundle\Form\Type\ModelAutocompleteType
            tags:
                - { name: form.type, alias: sonata_type_model_autocomplete }

    oxa.sonata.admin.resizer.webp:
        class: Oxa\Sonata\AdminBundle\Resizer\WebpResizer
        arguments: ['@sonata.media.adapter.image.gd', 'outbound', '@sonata.media.metadata.proxy']
