services:
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - {name: doctrine.event_listener, event: onFlush, priority: 0}
            - {name: doctrine.event_listener, event: loadClassMetadata}

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    oxa.listener.user_crud_action:
        class: Oxa\Sonata\AdminBundle\EventListener\UserCRUDActionListener
        arguments: [@security.token_storage]
        tags:
            - {name: doctrine.event_listener, event: onFlush, priority: 1}

    oxa.sonata.manager.admin_manager:
        class: Oxa\Sonata\AdminBundle\Manager\AdminManager
        calls:
            - [ setContainer, [ '@service_container' ] ]

    oxa.sonata.twig.admin_extension:
        class: Oxa\Sonata\AdminBundle\Twig\AdminExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: twig.extension, alias: admin_extension}