<?php

namespace Domain\ReportBundle\Repository;

use Oxa\Sonata\AdminBundle\Util\Helpers\AdminHelper;
use Doctrine\ORM\EntityRepository;

/**
 * BusinessOverviewReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessOverviewReportRepository extends EntityRepository
{
    /**
     * Used to be shown in export files
     * @var array
     */
    private $datePeriod = [
        'start' => '-',
        'end'   => '-',
    ];

    /**
     * business views per date period query builder
     *
     * @param array $params
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function getBusinessOverviewReportQb(array $params = [])
    {
        $qb = $this->createQueryBuilder('bor');

        // do not use pagination for Per month filter option
        if (!isset($params['periodOption']) || $params['periodOption'] != AdminHelper::PERIOD_OPTION_CODE_PER_MONTH) {
            // manage pagination
            if (isset($params['perPage']) && isset($params['page'])) {
                $first = ($params['page'] - 1) * $params['perPage'];
                $qb->setMaxResults($params['perPage']);
                $qb->setFirstResult($first);
            }
        }

        // filter by date
        if (isset($params['date']) && !empty($params['date']['start']) && !empty($params['date']['end'])) {
            $startDate = new \DateTime($params['date']['start']);
            $endDate   = new \DateTime($params['date']['end']);

            $this->datePeriod = [
                'start' => $params['date']['start'],
                'end'   => $params['date']['end'],
            ];

            $qb->andWhere('bor.date >= :startDate')
                ->setParameter('startDate', $startDate)
            ;

            $qb->andWhere('bor.date <= :endDate')
                ->setParameter('endDate', $endDate)
            ;
        }

        if (isset($params['dateTime'])) {
            $qb->andWhere('bor.date = :date')
                ->setParameter('date', $params['dateTime'])
            ;
        }

        if (!empty($params['businessProfileId'])) {
            $qb->andWhere('bor.businessProfile IN (:businessIds)')
                ->setParameter('businessIds', $params['businessProfileId'])
            ;
        }

        $qb->orderBy('bor.date');

        return $qb;
    }

    /**
     * business views per date period
     *
     * @param array $params
     *
     * @return array
     */
    public function getBusinessOverviewReportData(array $params = [])
    {
        $qb = $this->getBusinessOverviewReportQb($params);

        $results = $qb->getQuery()->getResult();

        return [
            'results'    => $results,
            'datePeriod' => $this->datePeriod
        ];
    }

    public function getBusinessOverviewReportByParams(array $params = [])
    {
        $qb = $this->getBusinessOverviewReportQb($params);

        return $qb->getQuery()->getResult();
    }
}
