<?php

namespace Domain\ReportBundle\Repository;

use Oxa\Sonata\AdminBundle\Util\Helpers\AdminHelper;

/**
 * BusinessOverviewReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessOverviewReportRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Used to be shown in export files
     * @var array
     */
    private $datePeriod = [
        'start' => '-',
        'end'   => '-',
    ];

    /**
     * @param array $params
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function getBusinessOverviewReportQuery(array $params = [])
    {
        $query = $this->getEntityManager()
            ->getRepository('DomainReportBundle:BusinessOverviewReport')
            ->createQueryBuilder('bor')
        ;

        // do not use pagination for Per month filter option
        if (!isset($params['periodOption']) || $params['periodOption'] != AdminHelper::PERIOD_OPTION_CODE_PER_MONTH) {
            // manage pagination
            if (isset($params['perPage']) && isset($params['page'])) {
                $first = ($params['page'] - 1) * $params['perPage'];
                $query->setMaxResults($params['perPage']);
                $query->setFirstResult($first);
            }
        }

        // filter by date
        if (
            isset($params['date']) &&
            !empty($params['date']['start']) &&
            !empty($params['date']['end'])
        ) {
            $startDate = new \DateTime($params['date']['start']);
            $endDate =  new \DateTime($params['date']['end']);

            $this->datePeriod = [
                'start' => $params['date']['start'],
                'end' => $params['date']['end'],
            ];

            $endDate->modify('1 day');

            $query->andWhere("bor.date >= :startDate")
                ->setParameter('startDate', $startDate)
            ;

            $query->andWhere("bor.date < :endDate")
                ->setParameter('endDate', $endDate)
            ;
        }

        return $query;
    }

    /**
     * Visitors for each category per date period
     *
     * @param array $params
     * @return array
     */
    public function getBusinessOverviewReportData(array $params = [])
    {
        $query = $this->getBusinessOverviewReportQuery($params);

        $results = $query
            ->select('bor')
            ->getQuery()
            ->getResult()
        ;

        return [
            'results' => $results,
            'datePeriod' => $this->datePeriod
        ];
    }
}
