<?php

namespace Domain\ReportBundle\Repository;

/**
 * CategoryReportCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryReportCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
