<?php

namespace Domain\ReportBundle\Repository;

/**
 * CategoryReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryReportRepository extends \Doctrine\ORM\EntityRepository
{
}
