<?php

namespace Domain\ReportBundle\Repository;

/**
 * SearchLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchLogRepository extends \Doctrine\ORM\EntityRepository
{
}
