<?php

namespace Domain\ReportBundle\Repository;

/**
 * SubscriptionReportSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionReportSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
