<?php

namespace Domain\ReportBundle\Repository;

/**
 * SubscriptionReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionReportRepository extends \Doctrine\ORM\EntityRepository
{
}
