<?php

namespace Domain\ReportBundle\Repository;

/**
 * ViewAndImpressionReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewAndImpressionReportRepository extends \Doctrine\ORM\EntityRepository
{
}
