<?php

namespace Oxa\VideoBundle\Repository;

/**
 * VideoMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
