<?php

namespace Oxa\VideoBundle\Repository;

use Oxa\VideoBundle\Entity\VideoMedia;

/**
 * VideoMediaEmbedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoMediaEmbedRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param VideoMedia $videoMedia
     * @return null|object
     */
    public function findByMediaObjectWithoutDimensions(VideoMedia $videoMedia)
    {
        return $this->findOneBy([
            'media'          => $videoMedia,
            'autoDimensions' => true,
        ]);
    }

    /**
     * @param VideoMedia $videoMedia
     * @param int $height
     * @return null|object
     */
    public function findByMediaObjectAndHeight(VideoMedia $videoMedia, int $height)
    {
        return $this->findOneBy([
            'media'          => $videoMedia,
            'height'         => $height,
            'autoDimensions' => true,
        ]);
    }

    /**
     * @param VideoMedia $videoMedia
     * @param int $width
     * @return null|object
     */
    public function findByMediaObjectAndWidth(VideoMedia $videoMedia, int $width)
    {
        return $this->findOneBy([
            'media'          => $videoMedia,
            'width'          => $width,
            'autoDimensions' => true,
        ]);
    }

    /**
     * @param VideoMedia $videoMedia
     * @param int $width
     * @param int $height
     * @return null|object
     */
    public function findByMediaObjectWithDimensions(VideoMedia $videoMedia, int $width, int $height)
    {
        return $this->findOneBy([
            'media'  => $videoMedia,
            'width'  => $width,
            'height' => $height,
        ]);
    }
}
