<?php

namespace Oxa\VideoBundle\Repository;

/**
 * VideoMediaThumbnailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoMediaThumbnailRepository extends \Doctrine\ORM\EntityRepository
{
}
