services:
    oxa_elastic_search.manager.search:
        class: Oxa\ElasticSearchBundle\Manager\ElasticSearchManager
        arguments: ['@monolog.logger.elasticsearch']
        calls:
            - [ setConfigData, [ '%elastic_search.indexing_page%', '%elastic_search.host%' ] ]
