services:
    oxa_sonata_media.admin.media:
        class: Oxa\Sonata\MediaBundle\Admin\MediaAdmin
        arguments:
            - ~
            - Oxa\Sonata\MediaBundle\Entity\Media
            - OxaSonataMediaBundle:MediaAdmin
            - '@sonata.media.pool'
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Media}
        calls:
            - [ setTemplate, ['edit', 'OxaSonataMediaBundle:MediaAdmin:edit.html.twig']]

    sonata.media.doctrine.event_subscriber:
        class: Oxa\Sonata\MediaBundle\EventListener\MediaRemoveListener
        arguments:
            - '@service_container'
        tags:
            - {name: doctrine.event_subscriber}
