domain_emergency_main:
    resource: "@DomainEmergencyBundle/Resources/config/routing/emergency.yml"
    prefix:     /emergency

domain_emergency_redirect:
    resource: "@DomainEmergencyBundle/Resources/config/routing/redirect.yml"
    prefix:     /emergencia
