services:
    domain_business.admin.area:
        class: Domain\BusinessBundle\Admin\AreaAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Area, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Areas}

    domain_business.admin.locality:
        class: Domain\BusinessBundle\Admin\LocalityAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Locality, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Localities}

    domain_business.admin.neighborhood:
        class: Domain\BusinessBundle\Admin\NeighborhoodAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Neighborhood, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Neighborhoods}

    domain_business.admin.tag:
        class: Domain\BusinessBundle\Admin\TagAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Tag, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Tags}

    domain_business.admin.payment_method:
        class: Domain\BusinessBundle\Admin\PaymentMethodAdmin
        arguments: [~, Domain\BusinessBundle\Entity\PaymentMethod, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Payment Methods}

    domain_business.admin.csv_import_file:
        class: Domain\BusinessBundle\Admin\CSVImportFileAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CSVImportFile, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CSV Mass Import}

    domain_business.admin.subscription:
        class: Domain\BusinessBundle\Admin\SubscriptionAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Subscription, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Subscriptions}
        calls:
            - [setTranslationDomain, [ 'AdminDomainBusinessBundle' ] ]

    domain_business.admin.subscription_plan:
        class: Domain\BusinessBundle\Admin\SubscriptionPlanAdmin
        arguments: [~, Domain\BusinessBundle\Entity\SubscriptionPlan, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Subscription Plans}

    domain_business.admin.category:
        class: Domain\BusinessBundle\Admin\CategoryAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Category, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Categories}

    domain_business.admin.testimonial:
        class: Domain\BusinessBundle\Admin\TestimonialAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Testimonial, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Testimonials}

    domain_business.admin.business_profile:
        class: Domain\BusinessBundle\Admin\BusinessProfileAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfile, DomainBusinessBundle:BusinessProfileCRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profiles, audit: true}
        calls:
            - [setTranslationDomain, [ 'AdminDomainBusinessBundle' ] ]
            - [ setTemplate, ['edit', 'DomainBusinessBundle:Admin:edit.html.twig']]

    domain_business.admin.task:
        class: Domain\BusinessBundle\Admin\TaskAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Task, DomainBusinessBundle:TaskAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Tasks}
        calls:
            - [ setTemplate, [list, DomainBusinessBundle:TaskAdmin:list.html.twig]]
            - [ setTemplate, [edit, DomainBusinessBundle:TaskAdmin:edit.html.twig]]
            - [ setTasksManager, ['@domain_business.manager.tasks']]

    domain_business.admin.business_review:
        class: Domain\BusinessBundle\Admin\Review\BusinessReviewAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Review\BusinessReview, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Reviews}

    domain_business.admin.business_profile_has_media:
        class: Domain\BusinessBundle\Admin\Media\BusinessGalleryAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Media\BusinessGallery, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Gallery}

    domain_business.admin.address.country:
        class: Domain\BusinessBundle\Admin\Address\CountryAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Address\Country, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Countries}

    domain_business.admin.coupon:
        class: Domain\BusinessBundle\Admin\CouponAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Coupon, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Coupons}

    domain_business.admin.business_profile_phone:
        class: Domain\BusinessBundle\Admin\BusinessProfilePhoneAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfilePhone, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Phones}

    domain_business.admin.business_profile_keyword:
        class: Domain\BusinessBundle\Admin\BusinessProfileKeywordAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileKeyword, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Keywords}

    domain_business.admin.business_profile_alias:
        class: Domain\BusinessBundle\Admin\BusinessProfileAliasAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileAlias, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Aliases}

    domain_business.admin.business_profile_media_urls:
        class: Domain\BusinessBundle\Admin\BusinessProfileMediaUrlAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileMediaUrl, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Media URLs}
        calls:
            - [setPositionService, ['@pix_sortable_behavior.position']]

    domain_business.admin.neighborhood_zip:
        class: Domain\BusinessBundle\Admin\NeighborhoodZipAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Zip, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Zips}

    domain_business.admin.business_profile_working_hour:
        class: Domain\BusinessBundle\Admin\BusinessProfileWorkingHourAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileWorkingHour, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Working Hour}

    domain_business.admin.landing_page_short_cut:
        class: Domain\BusinessBundle\Admin\LandingPageShortCutAdmin
        arguments: [~, Domain\BusinessBundle\Entity\LandingPageShortCut, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Landing Page Shortcut}

    domain_business.admin.landing_page_short_cut_searches:
        class: Domain\BusinessBundle\Admin\LandingPageShortCutSearchAdmin
        arguments: [~, Domain\BusinessBundle\Entity\LandingPageShortCutSearch, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Landing Page Shortcut Searches}
        calls:
            - [setPositionService, ['@pix_sortable_behavior.position']]

    domain_business.admin.clickbait_title:
        class: Domain\BusinessBundle\Admin\ClickbaitTitleAdmin
        arguments: [~, Domain\BusinessBundle\Entity\ClickbaitTitle, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Clickbait Title}

    domain_business.admin.locality_pseudo:
        class: Domain\BusinessBundle\Admin\LocalityPseudoAdmin
        arguments: [~, Domain\BusinessBundle\Entity\LocalityPseudo, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Locality Pseudo}

    domain_business.admin.business_profile_extrs_search:
        class: Domain\BusinessBundle\Admin\BusinessProfileExtraSearchAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileExtraSearch, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Extra Search}

    domain_business.admin.business_custom_fields_section:
        class: Domain\BusinessBundle\Admin\CustomFields\SectionAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\Section, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Section}
        calls:
            - [setPositionService, ['@pix_sortable_behavior.position']]

    domain_business.admin.business_custom_fields_checkbox:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldCheckboxAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldCheckbox, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Checkbox}

    domain_business.admin.checkbox_collection:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldCheckboxCollectionAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldCheckboxCollection, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Checkbox Collection}

    domain_business.admin.business_custom_fields_text_area:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldTextAreaAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldTextArea, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Text Area}

    domain_business.admin.text_area_collection:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldTextAreaCollectionAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldTextAreaCollection, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Text Area Collection}

    domain_business.admin.business_custom_fields_radio_button:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldRadioButtonAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldRadioButton, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Radio Button}

    domain_business.admin.business_custom_fields_radio_button_item:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldRadioButtonItemAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldRadioButtonItem, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Radio Button item}
        calls:
            - [setPositionService, ['@pix_sortable_behavior.position']]

    domain_business.admin.radio_button_collection:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldRadioButtonCollectionAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldRadioButtonCollection, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Radio Button Collection}

    domain_business.admin.business_custom_fields_list:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldListAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldList, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: List}

    domain_business.admin.business_custom_fields_list_item:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldListItemAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldListItem, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: List item}
        calls:
            - [setPositionService, ['@pix_sortable_behavior.position']]

    domain_business.admin.list_collection:
        class: Domain\BusinessBundle\Admin\CustomFields\BusinessCustomFieldListCollectionAdmin
        arguments: [~, Domain\BusinessBundle\Entity\CustomFields\BusinessCustomFieldListCollection, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: List Collection}

    domain_business.admin.homepage_carousel:
        class: Domain\BusinessBundle\Admin\HomepageCarouselAdmin
        arguments: [~, Domain\BusinessBundle\Entity\HomepageCarousel, DomainBusinessBundle:HomepageCarouselCRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Homepage Carousel}
        calls:
            - [setPositionService, ['@pix_sortable_behavior.position']]
