services:
    domain_business.admin.area:
        class: Domain\BusinessBundle\Admin\AreaAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Area, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Areas}

    domain_business.admin.locality:
        class: Domain\BusinessBundle\Admin\LocalityAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Locality, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Localities}

    domain_business.admin.neighborhood:
        class: Domain\BusinessBundle\Admin\NeighborhoodAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Neighborhood, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Neighborhoods}

    domain_business.admin.tag:
        class: Domain\BusinessBundle\Admin\TagAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Tag, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Tags}

    domain_business.admin.payment_method:
        class: Domain\BusinessBundle\Admin\PaymentMethodAdmin
        arguments: [~, Domain\BusinessBundle\Entity\PaymentMethod, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Payment Methods}

    domain_business.admin.subscription:
        class: Domain\BusinessBundle\Admin\SubscriptionAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Subscription, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Subscriptions}
        calls:
            - [setTranslationDomain, [ 'AdminDomainBusinessBundle' ] ]

    domain_business.admin.subscription_plan:
        class: Domain\BusinessBundle\Admin\SubscriptionPlanAdmin
        arguments: [~, Domain\BusinessBundle\Entity\SubscriptionPlan, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Subscription Plans}

    domain_business.admin.category:
        class: Domain\BusinessBundle\Admin\CategoryAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Category, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Categories}

    domain_business.admin.business_profile:
        class: Domain\BusinessBundle\Admin\BusinessProfileAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfile, DomainBusinessBundle:BusinessProfileCRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profiles, audit: true}
        calls:
            - [setTranslationDomain, [ 'AdminDomainBusinessBundle' ] ]
            - [ setTemplate, ['edit', 'DomainBusinessBundle:Admin:edit.html.twig']]

    domain_business.admin.task:
        class: Domain\BusinessBundle\Admin\TaskAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Task, DomainBusinessBundle:TaskAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Tasks}
        calls:
            - [ setTemplate, [list, DomainBusinessBundle:TaskAdmin:list.html.twig]]
            - [ setTemplate, [edit, DomainBusinessBundle:TaskAdmin:edit.html.twig]]
            - [ setTasksManager, ['@domain_business.manager.tasks']]

    domain_business.admin.business_review:
        class: Domain\BusinessBundle\Admin\Review\BusinessReviewAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Review\BusinessReview, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Reviews}

    domain_business.admin.business_profile_has_media:
        class: Domain\BusinessBundle\Admin\Media\BusinessGalleryAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Media\BusinessGallery, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Gallery}

    domain_business.admin.address.country:
        class: Domain\BusinessBundle\Admin\Address\CountryAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Address\Country, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Countries}

    domain_business.admin.coupon:
        class: Domain\BusinessBundle\Admin\CouponAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Coupon, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Coupons}

    domain_business.admin.business_profile_phone:
        class: Domain\BusinessBundle\Admin\BusinessProfilePhoneAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfilePhone, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Phones}

    domain_business.admin.business_profile_keyword:
        class: Domain\BusinessBundle\Admin\BusinessProfileKeywordAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileKeyword, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Keywords}

    domain_business.admin.business_profile_alias:
        class: Domain\BusinessBundle\Admin\BusinessProfileAliasAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileAlias, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Aliases}

    domain_business.admin.neighborhood_zip:
        class: Domain\BusinessBundle\Admin\NeighborhoodZipAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Zip, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Zips}

    domain_business.admin.business_profile_working_hour:
        class: Domain\BusinessBundle\Admin\BusinessProfileWorkingHourAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileWorkingHour, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Working Hour}

    domain_business.admin.landing_page_short_cut:
        class: Domain\BusinessBundle\Admin\LandingPageShortCutAdmin
        arguments: [~, Domain\BusinessBundle\Entity\LandingPageShortCut, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Landing Page Shortcut}

    domain_business.admin.landing_page_short_cut_searches:
        class: Domain\BusinessBundle\Admin\LandingPageShortCutSearchAdmin
        arguments: [~, Domain\BusinessBundle\Entity\LandingPageShortCutSearch, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Landing Page Shortcut Searches}
        calls:
            - [setPositionService, ['@pix_sortable_behavior.position']]

    domain_business.admin.clickbait_banner:
        class: Domain\BusinessBundle\Admin\ClickbaitBannerAdmin
        arguments: [~, Domain\BusinessBundle\Entity\ClickbaitBanner, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Clickbait Banner}

    domain_business.admin.locality_pseudo:
        class: Domain\BusinessBundle\Admin\LocalityPseudoAdmin
        arguments: [~, Domain\BusinessBundle\Entity\LocalityPseudo, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Locality Pseudo}

    domain_business.admin.business_profile_extrs_search:
        class: Domain\BusinessBundle\Admin\BusinessProfileExtraSearchAdmin
        arguments: [~, Domain\BusinessBundle\Entity\BusinessProfileExtraSearch, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Business Profile Extra Search}
