domain_business_default:
    resource: "@DomainBusinessBundle/Resources/config/routing/default.yml"
    prefix: /

domain_business_profile:
    resource: "@DomainBusinessBundle/Resources/config/routing/profile.yml"
    prefix: /profile