domain_business_profile:
    resource: "@DomainBusinessBundle/Resources/config/routing/profile.yml"
    prefix: /

domain_business_reviews:
    resource: "@DomainBusinessBundle/Resources/config/routing/reviews.yml"
    prefix: /reviews

domain_business_images:
    resource: "@DomainBusinessBundle/Resources/config/routing/images.yml"
    prefix: /images

domain_business_videos:
    resource: "@DomainBusinessBundle/Resources/config/routing/videos.yml"
    prefix: /videos

domain_business_reports:
    resource: "@DomainBusinessBundle/Resources/config/routing/reports.yml"
    prefix: /reports

domain_business_admin_reports:
    resource: "@DomainBusinessBundle/Resources/config/routing/adminReports.yml"
    prefix: /admin/reports

domain_business_admin_reviews:
    resource: "@DomainBusinessBundle/Resources/config/routing/adminReviews.yml"
    prefix: /admin/reviews
