domain_business_default:
    resource: "@DomainBusinessBundle/Resources/config/routing/default.yml"
    prefix: /

domain_business_profile:
    resource: "@DomainBusinessBundle/Resources/config/routing/profile.yml"
    prefix: /profile

domain_business_images:
    resource: "@DomainBusinessBundle/Resources/config/routing/images.yml"
    prefix: /images

domain_business_videos:
    resource: "@DomainBusinessBundle/Resources/config/routing/videos.yml"
    prefix: /videos
