parameters:
    domain.business.task.crud.controller.class: Domain\BusinessBundle\Controller\TaskAdminController
    domain.business.task.admin.task.entity: Domain\BusinessBundle\Entity\Task

services:
    #managers section
    domain_business.manager.business_profile:
        class: Domain\BusinessBundle\Manager\BusinessProfileManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@domain_business.manager.category'
            - '@security.token_storage'
            - '@sonata_translation.listener.translatable'
            - '@form.factory'

    domain_business.manager.tasks:
        class: Domain\BusinessBundle\Manager\TasksManager
        arguments: ['@doctrine.orm.entity_manager', '@domain_business.manager.business_profile']

    domain_business.manager.address_manager:
        class: Domain\BusinessBundle\Manager\AddressManager
        calls:
            - [ setContainer, [ '@service_container' ] ]

    domain_business.manager.category:
        class: Domain\BusinessBundle\Manager\CategoryManager
        arguments: ['@doctrine.orm.entity_manager']

    #twig extensions
    domain_business.twig_extension.enum_labels_dispatcher:
        class: Domain\BusinessBundle\Twig\Extension\EnumLabelsDispatcherExtension
        public: false
        tags:
            -  { name: twig.extension }

    domain_business.twig_extension.business_profiles_changeset:
        class: Domain\BusinessBundle\Twig\Extension\BusinessProfilesChangesetExtension
        public: false
        tags:
            -  { name: twig.extension }
        calls:
            - [ setFormObject, [ '@domain_business.form.business_profile.free' ] ]
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]
            - [ setTranslatableListener, [ '@sonata_translation.listener.translatable' ] ]

    #form types section
    domain_business.form.type.google_map:
        class: Domain\BusinessBundle\Form\Type\GoogleMapType
        arguments:
            - '%ivory_google_map.map.class%'
        tags:
            - { name: form.type, alias: google_map }
        calls:
            - [ setConfig, [ '@oxa_config' ] ]

    domain_business.form.type.google_map_front:
        class: Domain\BusinessBundle\Form\Type\GoogleMapFrontType
        arguments:
            - '%ivory_google_map.map.class%'
        tags:
            - { name: form.type, alias: google_map_front }
        calls:
            - [ setConfig, [ '@oxa_config' ] ]

    domain_business.form.type.business_profile:
        class: Domain\BusinessBundle\Form\Type\BusinessProfileType
        arguments: [null]
        tags:
        - { name: form.type, alias: domain_business_bundle_business_profile_type }

    domain_business.form.type.business_profile.free:
        class: Domain\BusinessBundle\Form\Type\FreeBusinessProfileFormType
        arguments: [null]
        tags:
        - { name: form.type, alias: domain_business_bundle_free_business_profile_form_type }

    #forms section
    domain_business.form.business_profile:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [domain_business_bundle_business_profile_type, domain_business_bundle_business_profile_type]

    domain_business.form.business_profile.free:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - 'domain_business_bundle_free_business_profile_form_type'
            - 'domain_business_bundle_free_business_profile_form_type'

    #form handlers section
    domain_business.form.handler.business_profile:
        class: Domain\BusinessBundle\Form\Handler\BusinessProfileFormHandler
        scope: request
        arguments:
            - '@domain_business.form.business_profile'
            - '@request'

    domain_business.form.handler.business_profile.free:
        class: Domain\BusinessBundle\Form\Handler\FreeBusinessProfileFormHandler
        scope: request
        arguments:
            - '@domain_business.form.business_profile.free'
            - '@request'
            - '@domain_business.manager.business_profile'
            - '@domain_business.manager.tasks'
            - '@validator'

    #event listeners section
    domain_business.listener.subscription_listener:
        class: Domain\BusinessBundle\EventListener\DatetimePeriodStatusListener
        tags:
            - {name: doctrine.event_listener, event: onFlush, priority: 2}

    #services section
    domain_business.service.datetime_period_status_service:
        class: Domain\BusinessBundle\Service\DatetimePeriodStatusService
        arguments:
            - '@doctrine.orm.entity_manager'
