parameters:
    domain.business.task.crud.controller.class: Domain\BusinessBundle\Controller\TaskAdminController
    domain.business.task.admin.task.entity: Domain\BusinessBundle\Entity\Task

services:
    domain_business.manager.tasks:
        class: Domain\BusinessBundle\Manager\TasksManager
        arguments: ['@doctrine.orm.entity_manager']

    domain_business.twig_extension.enum_labels_dispatcher:
        class: Domain\BusinessBundle\Twig\Extension\EnumLabelsDispatcherExtension
        public: false
        tags:
            -  { name: twig.extension }

    domain_business.admin.task:
        class: Domain\BusinessBundle\Admin\TaskAdmin
        arguments: [~, Domain\BusinessBundle\Entity\Task, DomainBusinessBundle:TaskAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Tasks}
        calls:
            - [ setTemplate, [list, DomainBusinessBundle:TaskAdmin:list.html.twig]]
            - [ setTemplate, [edit, DomainBusinessBundle:TaskAdmin:edit.html.twig]]
            - [ setTasksManager, ['@domain_business.manager.tasks']]

    domain_business.form.type.google_map:
        class: Domain\BusinessBundle\Form\Type\GoogleMapType
        arguments:
            - '%ivory_google_map.map.class%'
        tags:
            - { name: form.type, alias: google_map }
        calls:
            - [ setConfig, [ '@oxa_config' ] ]

    domain_business.manager.address_manager:
        class: Domain\BusinessBundle\Manager\AddressManager
        calls:
            - [ setContainer, [ '@service_container' ] ]

    domain_business.manager.category:
        class: Domain\BusinessBundle\Manager\CategoryManager
        arguments: ['@doctrine.orm.entity_manager']

    domain_business.manager.business_profile:
        class: Domain\BusinessBundle\Manager\BusinessProfileManager
        arguments: ['@doctrine.orm.entity_manager', '@domain_business.manager.category']
