services:
    domain_business.manager.tasks:
        class: Domain\BusinessBundle\Manager\TasksManager
        arguments: ['@doctrine.orm.entity_manager']

    domain_business.form.type.google_map:
        class: Domain\BusinessBundle\Form\Type\GoogleMapType
        arguments:
            - '%ivory_google_map.map.class%'
        tags:
            - { name: form.type, alias: google_map }
        calls:
            - [ setConfig, [ '@oxa_config' ] ]

    domain_business.manager.address_manager:
        class: Domain\BusinessBundle\Manager\AddressManager
        calls:
            - [ setContainer, [ '@service_container' ] ]

    domain_business.manager.category:
        class: Domain\BusinessBundle\Manager\CategoryManager
        arguments: ['@doctrine.orm.entity_manager']

    domain_business.manager.business_profile:
        class: Domain\BusinessBundle\Manager\BusinessProfileManager
        arguments: ['@doctrine.orm.entity_manager', '@domain_business.manager.category']

    domain_business.listener.subscription_listener:
        class: Domain\BusinessBundle\EventListener\DatetimePeriodStatusListener
        tags:
            - {name: doctrine.event_listener, event: onFlush, priority: 2}

    domain_business.service.datetime_period_status_service:
        class: Domain\BusinessBundle\Service\DatetimePeriodStatusService
        arguments:
            - '@doctrine.orm.entity_manager'
