parameters:
    domain.business.task.crud.controller.class: Domain\BusinessBundle\Controller\TaskAdminController
    domain.business.task.admin.task.entity: Domain\BusinessBundle\Entity\Task

services:
    #managers section
    domain_business.manager.business_profile:
        class: Domain\BusinessBundle\Manager\BusinessProfileManager
        arguments:
            - '@service_container'

    domain_business.manager.tasks:
        class: Domain\BusinessBundle\Manager\TasksManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@domain_business.manager.business_profile'
            - '@domain_business.manager.review'
            - '@oxa.manager.users'
            - '@domain_site.mailer'

    domain_business.manager.business_gallery:
        class: Domain\BusinessBundle\Manager\BusinessGalleryManager
        arguments: ['@doctrine.orm.entity_manager', '@sonata.media.manager.media']

    domain_business.manager.address_manager:
        class: Domain\BusinessBundle\Manager\AddressManager
        calls:
            - [ setContainer, [ '@service_container' ] ]

    domain_business.manager.subscription_status_manager:
        class: Domain\BusinessBundle\Manager\SubscriptionStatusManager

    domain_business.manager.category:
        class: Domain\BusinessBundle\Manager\CategoryManager
        arguments: ['@doctrine.orm.entity_manager']

    domain_business.manager.locality:
        class: Domain\BusinessBundle\Manager\LocalityManager
        arguments: ['@doctrine.orm.entity_manager']

    domain_business.manager.review:
        class: Domain\BusinessBundle\Manager\BusinessReviewManager
        arguments: ['@doctrine.orm.entity_manager']

    #twig extensions
    domain_business.twig_extension.enum_labels_dispatcher:
        class: Domain\BusinessBundle\Twig\Extension\EnumLabelsDispatcherExtension
        public: false
        tags:
            -  { name: twig.extension }

    domain_business.twig_extension.business_profile:
        class: Domain\BusinessBundle\Twig\Extension\BusinessProfileExtension
        public: false
        tags:
            -  { name: twig.extension }
        calls:
            - [ setBusinessProfileManager, [ '@domain_business.manager.business_profile' ] ]
            - [ setTranslator, [ '@translator' ] ]
            - [ setBusinessProfileForm, [ '@domain_business.form.business_profile' ] ]

    domain_business.twig_extension.report:
        class: Domain\BusinessBundle\Twig\Extension\ReportExtension
        public: false
        tags:
            -  { name: twig.extension }
        calls:
            - [ setBusinessProfileManager, [ '@domain_business.manager.business_profile' ] ]

    #form types section
    domain_business.form.type.google_map:
        class: Domain\BusinessBundle\Form\Type\GoogleMapType
        arguments:
            - '%ivory_google_map.map.class%'
        tags:
            - { name: form.type, alias: google_map }
        calls:
            - [ setConfig, [ '@oxa_config' ] ]

    domain_business.form.type.google_map_front:
        class: Domain\BusinessBundle\Form\Type\GoogleMapFrontType
        arguments:
            - '%ivory_google_map.map.class%'
        tags:
            - { name: form.type, alias: google_map_front }
        calls:
            - [ setConfig, [ '@oxa_config' ] ]

    domain_business.form.type.business_profile:
        class: Domain\BusinessBundle\Form\Type\BusinessProfileFormType
        arguments: [null]
        tags:
            - { name: form.type, alias: domain_business_bundle_business_profile_form_type }
        calls:
            - [ setCurrentUser, [ '@session' ] ]

    domain_business.form.type.entity_hidden:
       class: Domain\BusinessBundle\Form\Type\EntityHiddenType
       arguments: ["@doctrine.orm.entity_manager"]
       tags:
            - { name: form.type }

    domain_business.form.type.review:
        class: Domain\BusinessBundle\Form\Type\BusinessReviewType
        arguments: [null]
        tags:
            - { name: form.type, alias: domain_business_bundle_business_review_type }

    domain_business.form.type.business_close_request:
        class: Domain\BusinessBundle\Form\Type\BusinessCloseRequestType
        arguments: [null]
        tags:
            - { name: form.type, alias: domain_business_bundle_business_close_request_type }

    #forms section
    domain_business.form.business_profile:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - 'domain_business_bundle_business_profile_form_type'
            - 'domain_business_bundle_business_profile_form_type'

    domain_business.form.review:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - 'domain_business_bundle_business_review_type'
            - 'domain_business_bundle_business_review_type'

    domain_business.form.business_close_request:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - 'domain_business_bundle_business_close_request_type'
            - 'domain_business_bundle_business_close_request_type'

    #form handlers section
    domain_business.form.handler.business_profile:
        class: Domain\BusinessBundle\Form\Handler\BusinessProfileFormHandler
        scope: request
        arguments:
            - '@domain_business.form.business_profile'
            - '@request'
            - '@domain_business.manager.business_profile'
            - '@domain_business.manager.tasks'
            - '@validator'
            - '@security.token_storage'
            - '@oxa.manager.users'

    domain_business.form.handler.review:
        class: Domain\BusinessBundle\Form\Handler\ReviewFormHandler
        scope: request
        arguments:
            - '@domain_business.form.review'
            - '@request'
            - '@domain_business.manager.review'
            - '@domain_business.manager.business_profile'
            - '@domain_business.manager.tasks'
            - '@security.token_storage'

    domain_business.form.handler.business_close_request:
        class: Domain\BusinessBundle\Form\Handler\BusinessCloseRequestFormHandler
        scope: request
        arguments:
            - '@domain_business.form.business_close_request'
            - '@request'
            - '@domain_business.manager.business_profile'
            - '@domain_business.manager.tasks'

    #event listeners section
    domain_business.listener.datetime_period_status_subscriber:
        class: Domain\BusinessBundle\EventListener\DatetimePeriodStatusSubscriber
        tags:
            - {name: doctrine.event_subscriber, connection: default, priority: 2}
        calls:
            - [ setSubscriptionStatusManager, [ '@domain_business.manager.subscription_status_manager' ] ]
    domain_business.listener.subscription_listener:
        class: Domain\BusinessBundle\EventListener\SubscriptionListener
        tags:
            - {name: doctrine.event_listener, event: postFlush, priority: 10}
        calls:
            - [ setSubscriptionStatusManager, [ '@domain_business.manager.subscription_status_manager' ] ]

    #services section
    domain_business.service.datetime_period_status_service:
        class: Domain\BusinessBundle\Service\DatetimePeriodStatusService
        arguments:
            - '@doctrine.orm.entity_manager'

    domain_business.twig.has_subscription_extension:
        class: Domain\BusinessBundle\Twig\Extension\HasSubscriptionExtension
        tags:
            - { name: twig.extension }

    domain_business.video:
        class: Domain\BusinessBundle\Manager\VideoManager
        arguments: ['@doctrine.orm.entity_manager']
