domain_search_index:
    path:   /
    defaults: { _controller: DomainSearchBundle:Search:index }
domain_search_autocomplete:
    path:   /autocomplete
    defaults: { _controller: DomainSearchBundle:Search:autocomplete }
domain_search_map:
    path:   /map
    defaults: { _controller: DomainSearchBundle:Search:map }
domain_search_compare:
    path:   /compare
    defaults: { _controller: DomainSearchBundle:Search:compare }
