services:
    oxa_geolocation.manager:
        class: Oxa\GeolocationBundle\Model\Geolocation\GeolocationManager
        arguments: ['@doctrine.orm.entity_manager', "@oxa_config", '@domain_business.manager.locality', '@domain_business.manager.business_profile']
