<?php

namespace Domain\MenuBundle\Repository;

use Domain\MenuBundle\Entity\Menu;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Menu[]
     */
    public function getMenuItems()
    {
        $menuObjects = $this->createQueryBuilder('m')
            ->select('m')
            ->getQuery()
            ->getArrayResult();

        $menuItems = [];
        foreach ($menuObjects as $menuObject) {
            /** @var Menu $menuObject */
            $menuItems[$menuObject->getCode()] = $menuObject;
        }

        return $menuItems;
    }
}
