<?php

namespace Domain\MenuBundle\Repository;

use Domain\MenuBundle\Entity\Menu;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Menu[]
     */
    public function getMenuItems()
    {
        $menuObjects = $this->createQueryBuilder('m')
            ->select('m')
            ->indexBy('m', 'm.code')
            ->getQuery()
            ->getResult();

        return $menuObjects;
    }
}
