# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        jsqueeze: ~
    assets:
        app_common_css:
            inputs:
                - 'redesign/css/normalize.css'
                - '../sass/_scss/infopaginas.scss'
                - 'assets/styles/select2.min.css'
                - 'bundles/oxavideo/css/video-js.5.8.8.css'
                - 'assets/styles/video-js-social-share.css'
                - 'assets/styles/font-awesome.min.css'
            output: 'assetic/app_common_css.css'
            filters:
                - scssphp
        app_common_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/require.js'
                - 'bundles/fosjsrouting/js/router.js'
                - '@DomainSiteBundle/Resources/public/scripts/vendors/modernizr-2.7.1.min.js'
                - '@DomainSiteBundle/Resources/public/scripts/modules/helper.js'
            filters:
                - jsqueeze
        require_common_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/common.js'
            filters:
                - jsqueeze
        require_homepage_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/homepage.js'
            filters:
                - jsqueeze
        require_business_profile_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/businessProfile.js'
            filters:
                - jsqueeze
        require_reports_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/reports.js'
            filters:
                - jsqueeze
        require_map_search_page_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/mapsearchpage.js'
            filters:
                - jsqueeze
        require_business_profile_view_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/businessProfileView.js'
            filters:
                - jsqueeze
        require_compare_search_page_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/comparesearchpage.js'
            filters:
                - jsqueeze
        require_user_profile_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/userProfile.js'
            filters:
                - jsqueeze
        video_share_js:
            inputs:
                - 'assets/scripts/video-js-social-share.js'
            filters:
                - jsqueeze