# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        jsqueeze: ~
    assets:
        app_common_css:
            inputs:
                - 'redesign/css/normalize.css'
                - '../sass/_scss/infopaginas.scss'
                - 'assets/styles/select2.min.css'
                - 'bundles/oxavideo/css/video-js.5.8.8.css'
                - 'assets/styles/video-js-social-share.css'
                - 'assets/styles/font-awesome.min.css'
            output: 'assetic/app_common_css.css'
            filters:
                - scssphp
        app_emergency_css:
            inputs:
                - 'bundles/domainemergency/css/emergency.css'
            output: 'assetic/app_emergency_css.css'
            filters:
                - scssphp
        app_common_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/require.js'
                - 'bundles/fosjsrouting/js/router.js'
                - '@DomainSiteBundle/Resources/public/scripts/vendors/modernizr-2.7.1.min.js'
                - '@DomainSiteBundle/Resources/public/scripts/modules/helper.js'
            filters:
                - jsqueeze
        app_emergency_js:
            inputs:
                - 'bundles/fosjsrouting/js/router.js'
                - 'bundles/domainsite/scripts/vendors/jquery.min.js'
                - 'bundles/domainemergency/scripts/emergencyCatalog.js'
            filters:
                - jsqueeze
        require_common_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/common.js'
            filters:
                - jsqueeze
        require_homepage_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/homepage.js'
            filters:
                - jsqueeze
        require_ads_handler_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/ads.js'
            filters:
                - jsqueeze
        require_business_profile_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/businessProfile.js'
            filters:
                - jsqueeze
        require_reports_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/reports.js'
            filters:
                - jsqueeze
        require_map_search_page_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/mapsearchpage.js'
            filters:
                - jsqueeze
        require_business_profile_view_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/businessProfileView.js'
            filters:
                - jsqueeze
        require_compare_search_page_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/comparesearchpage.js'
            filters:
                - jsqueeze
        require_user_profile_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/userProfile.js'
            filters:
                - jsqueeze
        video_share_js:
            inputs:
                - 'assets/scripts/video-js-social-share.js'
            filters:
                - jsqueeze
        main_redesign_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/main.js'
            output: 'assetic/js/modules/main.min.js'
            filters:
                - jsqueeze
        profile_redesign_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/profile.js'
            output: 'assetic/js/modules/profile.min.js'
            filters:
                - jsqueeze
        maps_redesign_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/mapsearchpage.js'
            output: 'assetic/js/modules/mapSearchPage.min.js'
            filters:
                - jsqueeze
        tools_reset_password_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/resetPassword.js'
            output: 'assetic/js/modules/tools/resetPassword.min.js'
            filters:
                - jsqueeze
        tools_star_rating_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/star-rating.js'
            output: 'assetic/js/modules/tools/starRating.min.js'
            filters:
                - jsqueeze
        tools_search_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/search.js'
            output: 'assetic/js/modules/tools/search.min.js'
            filters:
                - jsqueeze
        tools_geolocation_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/geolocation.js'
            output: 'assetic/js/modules/tools/geolocation.min.js'
            filters:
                - jsqueeze
        tools_search_menu_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/searchMenu.js'
            output: 'assetic/js/modules/tools/searchMenu.min.js'
            filters:
                - jsqueeze
        tools_login_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/login.js'
            output: 'assetic/js/modules/tools/login.min.js'
            filters:
                - jsqueeze
        tools_registration_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/registration.js'
            output: 'assetic/js/modules/tools/registration.min.js'
            filters:
                - jsqueeze
        require_feedback_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/feedback.js'
            output: 'assetic/js/modules/tools/feedback.min.js'
            filters:
                - jsqueeze
        abstract_view_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/abstract/view.js'
            output: 'assetic/js/abstract/view.min.js'
            filters:
                - jsqueeze
        tools_spin_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/spin.js'
            output: 'assetic/js/modules/tools/spin.min.js'
            filters:
                - jsqueeze
        tools_directions_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/directions.js'
            output: 'assetic/js/modules/tools/directions.min.js'
            filters:
                - jsqueeze
        tools_select_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/select.js'
            output: 'assetic/js/modules/tools/select.min.js'
            filters:
                - jsqueeze
        tools_map_spin_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/mapspin.js'
            output: 'assetic/js/modules/tools/mapSpin.min.js'
            filters:
                - jsqueeze
        tools_report_tracker_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/reportTracker.js'
            output: 'assetic/js/modules/tools/reportTracker.min.js'
            filters:
                - jsqueeze
        tools_slider_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/slider.js'
            output: 'assetic/js/modules/tools/slider.min.js'
            filters:
                - jsqueeze
        tools_redirect_js:
            inputs:
                - '@DomainSiteBundle/Resources/public/scripts/modules/tools/redirect.js'
            output: 'assetic/js/modules/tools/redirect.min.js'
            filters:
                - jsqueeze
        tools_interactions_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/tools/interactions.js'
            output: 'assetic/js/modules/tools/interactions.min.js'
            filters:
                - jsqueeze
        tools_business_form_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/tools/form.js'
            output: 'assetic/js/modules/tools/form.min.js'
            filters:
                - jsqueeze
        tools_business_phone_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/tools/phones.js'
            output: 'assetic/js/modules/tools/phones.min.js'
            filters:
                - jsqueeze
        tools_business_working_hours_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/tools/workingHours.js'
            output: 'assetic/js/modules/tools/workingHours.min.js'
            filters:
                - jsqueeze
        tools_business_form_errors_handler_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/tools/formErrorsHandler.js'
            output: 'assetic/js/modules/tools/formErrorsHandler.min.js'
            filters:
                - jsqueeze
        tools_business_images_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/tools/images.js'
            output: 'assetic/js/modules/tools/images.min.js'
            filters:
                - jsqueeze
        tools_business_videos_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/modules/tools/videos.js'
            output: 'assetic/js/modules/tools/videos.min.js'
            filters:
                - jsqueeze
        user_google_map_js:
            inputs:
                - '@DomainBusinessBundle/Resources/public/scripts/google_map.js'
            output: 'assetic/js/googleMap.min.js'
            filters:
                - jsqueeze
