stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sortable: true
            translatable: true
            sluggable: true
            loggable: true