stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sortable: true
            translatable: true
            sluggable: true
            loggable: true

sonata_admin:
    extensions:
        j_maitan_sonata_media_crop.crop.extension:
            implements:
                - Sonata\MediaBundle\Model\MediaInterface

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                replace: Oxa\Sonata\AdminBundle\DQL\ReplaceFunction
