#
# more information can be found here http://sonata-project.org/bundles/media
#

sonata_media:
    db_driver:       doctrine_orm # | doctrine_mongodb
    default_context: business_profile_logo
    class:
        media:              Oxa\Sonata\MediaBundle\Entity\Media
        gallery:            Oxa\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Oxa\Sonata\MediaBundle\Entity\GalleryHasMedia
    contexts:
        # when you add a new one or edit context name,
        # edit OxaMediaInterface constans
        business_profile_logo:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:    { width: 120, height: 120, quality: 100}
                normal:     { width: 300, height: 300, quality: 100}
        business_profile_images:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:   { width: 150, height: 150, quality: 100}
                normal:    { width: 500, height: 500, quality: 100}
        business_profile_background:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:   { width: 150, height: 150, quality: 100}
                normal:    { width: 500, height: 500, quality: 100}
        coupon:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:    { width: 150, height: 150, quality: 100}
                normal:     { width: 500, height: 500, quality: 100}
        banner:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                home:       { width: 120, height: 420, quality: 100}
                portal:     { width: 300, height: 250, quality: 100}
                serp:       { width: 728, height: 90, quality: 100}
                serp_boxed: { width: 250, height: 250, quality: 100}
        article:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:      { width: 150, height: 150, quality: 100}
                homepage:     { width: 312, height: 260, quality: 100}
                list:         { width: 500, height: 170, quality: 100}
    cdn:
        #define the public base url for the uploaded media
        server:
            path:      '%sonata_media.cdn.host%'
    filesystem:
        # define where the uploaded file will be stored
        s3:
            sdk_version: 3
            bucket:         '%amazon_aws_bucket_name%'
            accessKey:      '%amazon_aws_key%'
            secretKey:      '%amazon_aws_secret_key%'
            region:         '%amazon_aws_region%' # change if not using US Standard region
            directory:      'uploads/media/%sonata_media.cdn.folder%'
            acl:            public

    providers:
        image:
            service:    sonata.media.provider.image
            filesystem: sonata.media.filesystem.s3
            allowed_extensions: ['jpg', 'png', 'gif', 'jpeg']
            allowed_mime_types: ['image/pjpeg','image/jpeg','image/png','image/x-png', 'image/gif']
            thumbnail: sonata.media.thumbnail.format
        file:
            # the resizer must be set to false, otherwhise this can delete icon files from the fs
            resizer:    false

    resizer:
        simple:
#            mode:  outbound
            mode:  inset


