#
# more information can be found here http://sonata-project.org/bundles/media
#

sonata_media:
    db_driver:       doctrine_orm # | doctrine_mongodb
    default_context: business_profile_logo
    class:
        media:              Oxa\Sonata\MediaBundle\Entity\Media
        gallery:            Oxa\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Oxa\Sonata\MediaBundle\Entity\GalleryHasMedia
    contexts:
        # when you add a new one or edit context name,
        # edit OxaMediaInterface constans
        business_profile_logo:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:      { width: 120, height: 120, quality: 70, format: 'reference'}
                normal:       { width: 300, height: 300, quality: 70, format: 'reference'}
                preview_webp: { width: 120, height: 120, quality: 70, format: 'webp'}
                normal_webp:  { width: 300, height: 300, quality: 70, format: 'webp'}
                preview_jp2:  { width: 120, height: 120, quality: 70, format: 'jp2'}
                normal_jp2:   { width: 300, height: 300, quality: 70, format: 'jp2'}
        business_profile_images:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:      { width: 150, height: 150, quality: 70, format: 'reference'}
                normal:       { width: 500, height: 500, quality: 70, format: 'reference'}
                preview_webp: { width: 150, height: 150, quality: 70, format: 'webp'}
                normal_webp:  { width: 500, height: 500, quality: 70, format: 'webp'}
                preview_jp2:  { width: 150, height: 150, quality: 70, format: 'jp2'}
                normal_jp2:   { width: 500, height: 500, quality: 70, format: 'jp2'}
        business_profile_background:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:      { width: 150, height: 150, quality: 70, format: 'reference'}
                normal:       { width: 500, height: 500, quality: 70, format: 'reference'}
                preview_webp: { width: 150, height: 150, quality: 70, format: 'webp'}
                normal_webp:  { width: 500, height: 500, quality: 70, format: 'webp'}
                preview_jp2:  { width: 150, height: 150, quality: 70, format: 'jp2'}
                normal_jp2:   { width: 500, height: 500, quality: 70, format: 'jp2'}
        coupon:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview: { width: 150, height: 150, quality: 70, format: 'reference'}
                normal:  { width: 500, height: 500, quality: 70, format: 'reference'}
        article:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:       { width: 150, height: 150, quality: 70, format: 'reference'}
                homepage:      { width: 312, height: 260, quality: 70, format: 'reference'}
                list:          { width: 500, height: 170, quality: 70, format: 'reference'}
                normal:        { width: 500, height: 500, quality: 100, format: 'reference'}
                preview_webp:  { width: 150, height: 150, quality: 70, format: 'webp'}
                homepage_webp: { width: 312, height: 260, quality: 70, format: 'webp'}
                list_webp:     { width: 500, height: 170, quality: 70, format: 'webp'}
                normal_webp:   { width: 500, height: 500, quality: 100, format: 'webp'}
                preview_jp2:   { width: 150, height: 150, quality: 70, format: 'jp2'}
                homepage_jp2:  { width: 312, height: 260, quality: 70, format: 'jp2'}
                list_jp2:      { width: 500, height: 170, quality: 70, format: 'jp2'}
                normal_jp2:    { width: 500, height: 500, quality: 100, format: 'jp2'}
        article_images:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:      { width: 150, height: 150, quality: 100, format: 'reference'}
                normal:       { width: 500, height: 500, quality: 100, format: 'reference'}
                preview_webp: { width: 150, height: 150, quality: 100, format: 'webp'}
                normal_webp:  { width: 500, height: 500, quality: 100, format: 'webp'}
                preview_jp2:  { width: 150, height: 150, quality: 100, format: 'jp2'}
                normal_jp2:   { width: 500, height: 500, quality: 100, format: 'jp2'}
        page_background:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:      { width: 140, height: 70, quality: 70, format: 'reference'}
                normal:       { width: 1400, height: 700, quality: 70, format: 'reference'}
                preview_webp: { width: 140, height: 70, quality: 70, format: 'webp'}
                normal_webp:  { width: 1400, height: 700, quality: 70, format: 'webp'}
                preview_jp2:  { width: 140, height: 70, quality: 70, format: 'jp2'}
                normal_jp2:   { width: 1400, height: 700, quality: 70, format: 'jp2'}
        video_poster:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview:      { width: 75, height: 75, quality: 100, format: 'reference'}
                normal:       { width: 500, height: 500, quality: 70, format: 'reference'}
                preview_webp: { width: 75, height: 75, quality: 100, format: 'webp'}
                normal_webp:  { width: 500, height: 500, quality: 70, format: 'webp'}
                preview_jp2:  { width: 75, height: 75, quality: 100, format: 'jp2'}
                normal_jp2:   { width: 500, height: 500, quality: 70, format: 'jp2'}
        homepage_carousel:
            download:
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                normal:       { width: 444, height: 246, quality: 70, format: 'reference'}
                normal_webp:  { width: 444, height: 246, quality: 70, format: 'webp'}
                normal_jp2:   { width: 444, height: 246, quality: 70, format: 'jp2'}
    cdn:
        #define the public base url for the uploaded media
        server:
            path:      '%sonata_media.cdn.host%'
    filesystem:
        # define where the uploaded file will be stored
        s3:
            sdk_version: 3
            bucket:         '%amazon_aws_bucket_name%'
            accessKey:      '%amazon_aws_key%'
            secretKey:      '%amazon_aws_secret_key%'
            region:         '%amazon_aws_region%' # change if not using US Standard region
            directory:      'uploads/media/%sonata_media.cdn.folder%'
            acl:            public
            cache_control:  max-age=5184000 # 60 days

    providers:
        image:
            service:    sonata.media.provider.image
            filesystem: sonata.media.filesystem.s3
            allowed_extensions: ['jpg', 'png', 'gif', 'jpeg']
            allowed_mime_types: ['image/pjpeg','image/jpeg','image/png','image/x-png', 'image/gif']
            thumbnail: sonata.media.thumbnail.format
            resizer: oxa.sonata.admin.resizer.format_conversion
        file:
            # the resizer must be set to false, otherwhise this can delete icon files from the fs
            resizer:    false

    resizer:
        simple:
#            mode:  outbound
            mode:  inset


