sonata_translation:
    locales: %locales%
    default_locale: %locale%
    # here enable the types you need
    gedmo:
        enabled: true
#    knplabs:
#        enabled: true
    #phpcr:
    #    enabled: true

