sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata_translation.block.locale_switcher:
            contexts: [admin]

sonata_admin:
    title: Ingopaginas
    title_logo: oxagile.png
    templates:
        layout: OxaSonataAdminBundle::layout.html.twig
        list:   OxaSonataAdminBundle:CRUD:list.html.twig
        edit:   OxaSonataAdminBundle:CRUD:edit.html.twig
        show:   OxaSonataAdminBundle:CRUD:show.html.twig
        base_list_field:   OxaSonataAdminBundle:CRUD:base_list_field.html.twig
        batch_confirmation:   OxaSonataAdminBundle:CRUD:batch_confirmation.html.twig
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        groups:
            sonata.admin.group.user:
                label: Users
                icon: <i class="fa fa-users"></i>
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
#            sonata.admin.group.media:
#                label: Media
#                icon: <i class="fa fa-pencil-square-o"></i>
#                items:
#                    - sonata.media.admin.media
#                    - sonata.media.admin.gallery
