# Twig Constant Configuration
twig:
    globals:
#       const of Category class
        CATEGORY_LEVEL_1: 1
        CATEGORY_LEVEL_2: 2
        CATEGORY_LEVEL_3: 3

        CATEGORY_DEFAULT_LEVEL:    1
        SUBCATEGORY_DEFAULT_LEVEL: 2
        CATEGORY_MAX_LEVEL:        3

        PAGINATION_RADIUS: 2

#        const of BusinessProfileFormHandler class
        MESSAGE_BUSINESS_PROFILE_FLASH_GROUP: 'success'

#        const of BusinessProfile class
        BUSINESS_PROFILE_FIELD:
            SEO_TITLE:       'seoTitle'
            SEO_DESCRIPTION: 'seoDescription'
            NAME:            'name'
            NAME_ES:         'nameEs'
            NAME_EN:         'nameEn'
            DESCRIPTION:     'description'
            DESCRIPTION_ES:  'descriptionEs'
            DESCRIPTION_EN:  'descriptionEn'
            PRODUCT:         'product'
            BRANDS:          'brands'
            WORKING_HOURS:   'workingHours'
            SLOGAN:          'slogan'

#        const of PaymentMethod class
        PAYMENT_METHOD_TYPE:
            CASH:       'cash'
            CHECK:      'check'
            PAYPAL:     'paypal'
            ATH_MOVIL:  'ath_movil'
            ONLINE:     'online'
            DEBIT:      'debit'

#       const types of ChangeSetCalculator class
        CHANGE_SET_TYPE:
            PROPERTY_IMAGE_PROPERTY_UPDATE: 'PROPERTY_IMAGE_PROPERTY_UPDATE'
            PROPERTY_CHANGE:                'PROPERTY_CHANGE'
            PROPERTY_ADD:                   'PROPERTY_ADD'
            PROPERTY_REMOVE:                'PROPERTY_REMOVE'
            IMAGE_ADD:                      'IMAGE_ADD'
            IMAGE_REMOVE:                   'IMAGE_REMOVE'
            VIDEO_ADD:                      'VIDEO_ADD'
            VIDEO_REMOVE:                   'VIDEO_REMOVE'
            VIDEO_UPDATE:                   'VIDEO_UPDATE'
            LOGO_ADD:                       'LOGO_ADD'
            LOGO_REMOVE:                    'LOGO_REMOVE'
            LOGO_UPDATE:                    'LOGO_UPDATE'
            BACKGROUND_ADD:                 'BACKGROUND_ADD'
            BACKGROUND_REMOVE:              'BACKGROUND_REMOVE'
            BACKGROUND_UPDATE:              'BACKGROUND_UPDATE'