fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Oxa\Sonata\UserBundle\Entity\User
    group:
        group_class:   Oxa\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

sonata_user:
    class:
        user: Oxa\Sonata\UserBundle\Entity\User
        group: Oxa\Sonata\UserBundle\Entity\Group
    admin:
        user:
            class: Oxa\Sonata\UserBundle\Admin\UserAdmin
            controller: OxaSonataAdminBundle:CRUD
        group:
            class: Oxa\Sonata\UserBundle\Admin\GroupAdmin
            controller: OxaSonataAdminBundle:CRUD
