fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

sonata_user:
    admin:
        user:
            class: Application\Sonata\UserBundle\Admin\UserAdmin
#            controller: AppBundle:SonataAdmin/DefaultEntityCRUD
        group:
            class: Application\Sonata\UserBundle\Admin\GroupAdmin
#            controller: AppBundle:SonataAdmin/DefaultEntityCRUD
