services:
    domain_page.manager.page:
        class: Domain\PageBundle\Model\Manager\PageManager
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [ setSeoParams, [ '%seo_custom_settings%' ] ]

    domain_page.feedback.form.handler:
        class: Domain\PageBundle\Form\Handler\FeedbackFormHandler
        scope: request
        arguments:
            - '@domain_page.feedback.form'
            - '@request'
            - '@translator.default'
            - '@domain_report.manager.feedback_report_manager'

    domain_page.feedback.form.type:
        class: Domain\PageBundle\Form\Type\FeedbackFormType
        arguments: [null]
        tags:
        - { name: form.type, alias: domain_page_bundle_feedback_form_type }

    domain_page.feedback.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [domain_page_bundle_feedback_form_type, domain_page_bundle_feedback_form_type]
