domain_business_admin_validation_business_name:
    path:     /business/{id}/similar-name
    defaults: { _controller: DomainBusinessBundle:Profile:nameValidation, id: 0 }
    options:
        expose: true
