domain_business_reports_index:
    path:     /{businessProfileId}
    defaults: { _controller: DomainBusinessBundle:Reports:index }

domain_business_reports_business_overview:
    path:     /overview/{businessProfileId}
    defaults: { _controller: DomainBusinessBundle:Reports:overview }

domain_business_reports_business_impressions:
    path:     /impressions/{businessProfileId}
    defaults: { _controller: DomainBusinessBundle:Reports:impressions }

domain_business_reports_business_keywords:
    path:     /keywords/{businessProfileId}
    defaults: { _controller: DomainBusinessBundle:Reports:keywords }
