domain_business_reports_index:
    path:     /{businessProfileId}
    defaults: { _controller: DomainBusinessBundle:Reports:index }

domain_business_reports_business_overview_data:
     path:     /data/overview
     defaults: { _controller: DomainBusinessBundle:Reports:overview }
     options:
        expose: true

domain_business_reports_ad_usage_data:
     path:     /data/ad_usage
     defaults: { _controller: DomainBusinessBundle:Reports:adUsage }
     options:
        expose: true

domain_business_reports_keywords_data:
     path:     /data/keywords
     defaults: { _controller: DomainBusinessBundle:Reports:keywords }
     options:
        expose: true

domain_business_reports_interactions_track:
     path:     /track/interactions
     defaults: { _controller: DomainBusinessBundle:Reports:interactionsTrack }
     options:
        expose: true

domain_business_reports_excel_export:
     path:     /export/excel
     defaults: { _controller: DomainBusinessBundle:Reports:excelExport }

domain_business_reports_pdf_export:
     path:     /export/pdf
     defaults: { _controller: DomainBusinessBundle:Reports:pdfExport }

domain_business_reports_api_overview:
     path:     /api/overview
     defaults: { _controller: DomainBusinessBundle:Api:overview }

domain_business_reports_api_keywords:
     path:     /api/keywords
     defaults: { _controller: DomainBusinessBundle:Api:keywords }
