domain_business_review_save:
    path:     /save
    defaults: { _controller: DomainBusinessBundle:Reviews:save }
    options:
        expose: true

domain_business_reviews_list:
    path: /list/{businessProfileId}
    defaults: { _controller: DomainBusinessBundle:Reviews:list }