domain_business_local_videos_upload:
    path:     /local/upload
    defaults: { _controller: DomainBusinessBundle:Videos:localFileUpload }
    options:
        exposed: true

domain_business_remote_videos_upload:
    path:     /remote/upload
    defaults: { _controller: DomainBusinessBundle:Videos:remoteFileUpload }
    options:
        exposed: true