services:
    domain_article.admin.article:
        class: Domain\ArticleBundle\Admin\ArticleAdmin
        arguments: [~, Domain\ArticleBundle\Entity\Article, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Articles}
    domain_article.admin.article_has_media:
        class: Domain\ArticleBundle\Admin\Media\ArticleGalleryAdmin
        arguments: [~, Domain\ArticleBundle\Entity\Media\ArticleGallery, OxaSonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Article Gallery}
        calls:
             - [setPositionService, ['@pix_sortable_behavior.position']]
    domain_article.manager.article:
        class: Domain\ArticleBundle\Model\Manager\ArticleManager
        arguments: ['@service_container']

    domain_article.manager.api:
        class: Domain\ArticleBundle\Model\Manager\ArticleApiManager
        arguments: ['@service_container']

    domain_article.twig_extension.cut_body:
        class: Domain\ArticleBundle\Twig\Extension\CutBodyExtension
        public: false
        tags:
            -  { name: twig.extension }
