<?php

namespace Oxa\ConfigBundle\Model;

/**
 * Interface ConfigInterface
 * @package Oxa\ConfigBundle\Model
 */
interface ConfigInterface
{
    public const DEFAULT_TITLE                     = 'DEFAULT_TITLE';
    public const DEFAULT_META_DESCRIPTION          = 'META_DESCRIPTION';
    public const DEFAULT_META_KEYWORDS             = 'META_KEYWORDS';
    public const DEFAULT_EMAIL_ADDRESS             = 'DEFAULT_EMAIL_ADDRESS';
    public const MAIL_REGISTRATION_TEMPLATE        = 'MAIL_REGISTRATION_TEMPLATE';
    public const MAIL_NEW_MERCHANT_TEMPLATE        = 'MAIL_NEW_MERCHANT_TEMPLATE';
    public const MAIL_RESET_PASSWORD_TEMPLATE      = 'MAIL_RESET_PASSWORD_TEMPLATE';
    public const MAIL_TEMPLATE_TO_USER             = 'MAIL_TEMPLATE_TO_USER';
    public const MAIL_CHANGE_WAS_REJECTED          = 'MAIL_CHANGE_WAS_REJECTED';
    public const MAPBOX_API_KEY                    = 'MAPBOX_API_KEY';
    public const DEFAULT_MAP_COORDINATE_LATITUDE   = 'DEFAULT_MAP_COORDINATE_LATITUDE';
    public const DEFAULT_MAP_COORDINATE_LONGITUDE  = 'DEFAULT_MAP_COORDINATE_LONGITUDE';
    public const DEFAULT_RESULTS_PAGE_SIZE         = 'DEFAULT_RESULTS_PAGE_SIZE';
    public const DEFAULT_SEARCH_CITY               = 'DEFAULT_SEARCH_CITY';
    public const YOUTUBE_ACCESS_TOKEN              = 'YOUTUBE_ACCESS_TOKEN';
    public const YOUTUBE_ERROR_EMAIL_TEMPLATE      = 'YOUTUBE_ERROR_EMAIL_TEMPLATE';
    public const ARTICLE_API_ERROR_EMAIL_TEMPLATE  = 'ARTICLE_API_ERROR_EMAIL_TEMPLATE';
    public const SEARCH_ADS_ALLOWED                = 'SEARCH_ADS_ALLOWED';
    public const SEARCH_ADS_MAX_PAGE               = 'SEARCH_ADS_MAX_PAGE';
    public const SEARCH_ADS_PER_PAGE               = 'SEARCH_ADS_PER_PAGE';
    public const MAIL_REPORT_EXPORT_PROCESSED      = 'MAIL_REPORT_EXPORT_PROCESSED';
    public const FEEDBACK_EMAIL_ADDRESS            = 'FEEDBACK_EMAIL_ADDRESS';
    public const FEEDBACK_EMAIL_SUBJECT            = 'FEEDBACK_EMAIL_SUBJECT';
    public const REPORT_PROBLEM_EMAIL_ADDRESS      = 'REPORT_PROBLEM_EMAIL_ADDRESS';
    public const REPORT_PROBLEM_EMAIL_SUBJECT      = 'REPORT_PROBLEM_EMAIL_SUBJECT';
    public const EMERGENCY_SITUATION_ON            = 'EMERGENCY_SITUATION_ON';
    public const EMERGENCY_CATALOG_ORDER_BY_ALPHABET   = 'EMERGENCY_CATALOG_ORDER_BY_ALPHABET';
    public const GOOGLE_OPTIMIZATION_CONTAINER_ID      = 'GOOGLE_CONTAINER_ID';
    public const SUGGEST_CATEGORY_MINIMUM_MATCH        = 'SUGGEST_CATEGORY_MINIMUM_MATCH';
    public const SUGGEST_LOCALITY_MINIMUM_MATCH        = 'SUGGEST_LOCALITY_MINIMUM_MATCH';
    public const STATUS_WAS_CHANGED_EMAIL_TEMPLATE     = 'STATUS_WAS_CHANGED_EMAIL_TEMPLATE';
    public const UPDATE_PROFILE_REQUEST_EMAIL_TEMPLATE = 'MAIL_UPDATE_PROFILE_REQUEST_TEMPLATE';
    public const UPDATE_PROFILE_REQUEST_EMAIL_ADDRESS  = 'UPDATE_PROFILE_REQUEST_EMAIL_ADDRESS';
    public const UPDATE_PROFILE_REQUEST_EMAIL_SUBJECT  = 'UPDATE_PROFILE_REQUEST_SUBJECT';
    public const IMPRESSIONS_FILTER_VALUE              = 'IMPRESSIONS_FILTER_VALUE';
    public const DIRECTIONS_FILTER_VALUE               = 'DIRECTIONS_FILTER_VALUE';
    public const CALLS_MOBILE_FILTER_VALUE             = 'CALLS_MOBILE_FILTER_VALUE';
    public const EXCEPTION_ERROR_TEMPLATE              = 'EXCEPTION_ERROR_TEMPLATE';
    public const EXCEPTION_ERROR_EMAIL_ADDRESS         = 'EXCEPTION_ERROR_EMAIL_ADDRESS';
    public const EXCEPTION_ERROR_EMAIL_SUBJECT         = 'EXCEPTION_ERROR_EMAIL_SUBJECT';
    public const HOMEPAGE_CAROUSEL_MAX_ELEMENT_COUNT   = 'HOMEPAGE_CAROUSEL_MAX_ELEMENT_COUNT';
    public const FOOTER_EMAIL                          = 'FOOTER_EMAIL';
    public const FOOTER_PHONE_NUMBER                   = 'FOOTER_PHONE_NUMBER';
    public const OFFICE_COORDINATES                    = 'OFFICE_COORDINATES';
    public const DELETE_PROFILE_ALERT_EMAIL_ADDRESS    = 'DELETE_PROFILE_ALERT_EMAIL_ADDRESS';
    public const DELETE_PROFILE_ALERT_EMAIL_SUBJECT    = 'DELETE_PROFILE_ALERT_EMAIL_SUBJECT';
    public const BUSINESS_PROFILE_POPUP_TIME_TO_APPEAR = 'BUSINESS_PROFILE_POPUP_TIME_TO_APPEAR';
}
