<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Application\Sonata\AdminBundle\Model\CopyableEntityInterface;
use Application\Sonata\AdminBundle\Model\DefaultEntityInterface;
use Application\Sonata\AdminBundle\Util\Traits\DefaultEntityTrait;
use Doctrine\ORM\Mapping as ORM;
use Sonata\UserBundle\Entity\BaseGroup as BaseGroup;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 *
 * @ORM\Table(name="fos_user_group")
 * @ORM\Entity()
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class Group extends BaseGroup implements CopyableEntityInterface, DefaultEntityInterface
{
    use DefaultEntityTrait;
    
    /**
     * @var integer $id
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function getMarkCopyPropertyName()
    {
        return 'name';
    }
}
