<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Oxa\Sonata\UserBundle\Entity;

use Oxa\Sonata\AdminBundle\Model\CopyableEntityInterface;
use Oxa\Sonata\AdminBundle\Model\DefaultEntityInterface;
use Oxa\Sonata\AdminBundle\Util\Traits\DefaultEntityTrait;
use Doctrine\ORM\Mapping as ORM;
use Sonata\UserBundle\Entity\BaseGroup as BaseGroup;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 *
 * @ORM\Table(name="fos_user_group")
 * @ORM\Entity(repositoryClass="Oxa\Sonata\UserBundle\Entity\Repository\GroupRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @UniqueEntity("code")
 */
class Group extends BaseGroup implements DefaultEntityInterface
{
    use DefaultEntityTrait;

    // codes are also used as priority in admin panel to know if an user is able to edit another user
    const CODE_ADMINISTRATOR    = 1; // Admin portal user
    const CODE_CONTENT_MANAGER  = 2; // Admin portal user
    const CODE_SALES_MANAGER    = 3; // Admin portal user
    const CODE_MERCHANT         = 4; // Customer, manages Businesses
    const CODE_CONSUMER         = 5; // Visitor, has site profile

    public static $groupRoles = [
        self::CODE_ADMINISTRATOR    => 'ROLE_ADMINISTRATOR',
        self::CODE_CONTENT_MANAGER  => 'ROLE_CONTENT_MANAGER',
        self::CODE_SALES_MANAGER    => 'ROLE_SALES_MANAGER',
        self::CODE_MERCHANT         => 'ROLE_MERCHANT',
        self::CODE_CONSUMER         => 'ROLE_CONSUMER',
    ];

    /**
     * @var integer $id
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="code", type="integer", nullable=false, options={"default" = 1})
     */
    protected $code;

    /**
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    protected $description;

    /**
     * @var User
     *
     * @ORM\OneToMany(targetEntity="Oxa\Sonata\UserBundle\Entity\User", mappedBy="role", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"createdAt" = "asc"})
     */
    protected $roleUsers;
    
    /**
     * Set code
     *
     * @param integer $code
     *
     * @return Group
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get code
     *
     * @return integer
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Group
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add roleUser
     *
     * @param \Oxa\Sonata\UserBundle\Entity\User $roleUser
     *
     * @return Group
     */
    public function addRoleUser(\Oxa\Sonata\UserBundle\Entity\User $roleUser)
    {
        $this->roleUsers[] = $roleUser;

        return $this;
    }

    /**
     * Remove roleUser
     *
     * @param \Oxa\Sonata\UserBundle\Entity\User $roleUser
     */
    public function removeRoleUser(\Oxa\Sonata\UserBundle\Entity\User $roleUser)
    {
        $this->roleUsers->removeElement($roleUser);
    }

    /**
     * Get roleUsers
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRoleUsers()
    {
        return $this->roleUsers;
    }
}
