<?php

namespace Oxa\WistiaBundle\Repository;

/**
 * WistiaMediaThumbnailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WistiaMediaThumbnailRepository extends \Doctrine\ORM\EntityRepository
{
}
