<?php

namespace Oxa\WistiaBundle\Repository;

/**
 * WistiaMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WistiaMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
