<?php

namespace Oxa\DfpBundle\Repository;

/**
 * DoubleClickSynchLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoubleClickSynchLogRepository extends \Doctrine\ORM\EntityRepository
{
}
