<?php

namespace Oxa\DfpBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;
use Domain\BusinessBundle\Entity\BusinessProfile;

/**
 * DoubleClickLineItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoubleClickLineItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     * @throws \Doctrine\ORM\Query\QueryException
     */
    public function getDoubleClickLineItemIds()
    {
        $qb = $this->createQueryBuilder('dc_li')
            ->select('dc_li.doubleClickLineItemId')
            ->indexBy('dc_li', 'dc_li.doubleClickLineItemId');

        return array_keys($qb->getQuery()->getArrayResult());
    }

    /**
     * @param BusinessProfile $businessProfile
     * @return array
     * @throws \Doctrine\ORM\Query\QueryException
     */
    public function getLineItemIdsByBusinessProfile(BusinessProfile $businessProfile)
    {
        $qb = $this->createQueryBuilder('dc_li');

        $qb->innerJoin('dc_li.doubleClickOrder', 'dc_o', Join::INNER_JOIN);
        $qb->innerJoin('dc_o.doubleClickCompany', 'dc_c', Join::INNER_JOIN);
        $qb->where('dc_c.businessProfile = :businessProfile');
        $qb->setParameter('businessProfile', $businessProfile);
        $qb->indexBy('dc_li', 'dc_li.doubleClickLineItemId');

        return array_keys($qb->getQuery()->getArrayResult());
    }
}
