<?php

namespace Oxa\DfpBundle\Repository;

/**
 * DoubleClickCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoubleClickCompanyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCompaniesIndexedByDcCompanyId()
    {
        $qb = $this->createQueryBuilder('dc_c');
        $qb->indexBy('dc_c', 'dc_c.doubleClickCompanyId');

        return $qb->getQuery()->getResult();
    }
}
