domain_site_home:
    resource: "@DomainSiteBundle/Resources/config/routes/homeControllerRoutes.yml"
    prefix:   /

domain_site_profile:
    resource: "@DomainSiteBundle/Resources/config/routes/profileControllerRoutes.yml"
    prefix:   /profile

domain_site_search:
    resource: "@DomainSiteBundle/Resources/config/routes/searchControllerRoutes.yml"
    prefix:   /search
