domain_site_home:
    resource: "@DomainSiteBundle/Resources/config/routes/homeControllerRoutes.yml"
    host: "{_locale}.{domain}"
    prefix:   /
    defaults:  { _locale: "%locale%", domain: "localhost" }
    requirements:
        _locale : '%route_locales%'
        domain:  "localhost"

domain_site_home_nolocale:
    resource: "@DomainSiteBundle/Resources/config/routes/homeControllerRoutes.yml"
    prefix:   /

domain_site_profile:
    resource: "@DomainSiteBundle/Resources/config/routes/profileControllerRoutes.yml"
    host: "{_locale}.{domain}"
    prefix:   /profile
    defaults:  { _locale: "%locale%", domain: "localhost" }
    requirements:
        _locale : '%route_locales%'
        domain:  "localhost"

domain_site_geolocation:
    resource: "@DomainSiteBundle/Resources/config/routes/geolocationControllerRoutes.yml"
    host: "{_locale}.{domain}"
    prefix:   /geolocation
    requirements:
        _locale : '%route_locales%'
        domain:  "localhost"

domain_site_geolocation_nolocale:
    resource: "@DomainSiteBundle/Resources/config/routes/geolocationControllerRoutes.yml"
    prefix:   /geolocation

domain_site_oauth:
    resource: "@DomainSiteBundle/Resources/config/routes/oauth.yml"
    prefix:   /oauth

domain_site_connect_service:
   path:     /login/service/{service}
   defaults: { _controller: DomainSiteBundle:Connect:connectService }