domain_site_home_nolocale:
    resource: "@DomainSiteBundle/Resources/config/routes/homeControllerRoutes.yml"
    prefix:   /

domain_site_auth:
    resource: "@DomainSiteBundle/Resources/config/routes/auth.yml"
    prefix:   /auth

domain_site_oauth:
    resource: "@DomainSiteBundle/Resources/config/routes/oauth.yml"
    prefix:   /

domain_site_user:
    resource: "@DomainSiteBundle/Resources/config/routes/user.yml"
    prefix:   /user

# 301 and 410 redirect for old urls

domain_site_redirect_qr:
    path:     /{path}.html
    defaults: { _controller: DomainSiteBundle:Redirect:index }
    requirements:
        path: .+

domain_site_consult:
    path:     /consulta
    defaults: { _controller: DomainSiteBundle:Redirect:consult }

domain_site_redirect_sign_up:
    path:     /sign_up
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: domain_site_home_index
        permanent: true

domain_site_redirect_sign_in:
    path:     /sign_in
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: domain_site_home_index
        permanent: true

domain_site_redirect_forgot:
    path:     /users/password/new
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: domain_site_home_index
        permanent: true

domain_site_redirect_manage_listings:
    path:     /manage-listings
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: domain_site_home_index
        permanent: true
