services:
    domain_site.manager.search:
        class: Domain\SiteBundle\Manager\SearchManager
        arguments: ['@doctrine.orm.entity_manager']
    domain_site.manager.geolocation:
        class: Domain\SiteBundle\Manager\GeolocationManager
        arguments: ['@doctrine.orm.entity_manager']
