#danvbe/UserBundle/Resources/services.yml
parameters:
    my_user_provider.class: Domain\SiteBundle\Security\Core\User\FOSUBUserProvider

services:
    domain_site.manager.search:
        class: Domain\SiteBundle\Manager\SearchManager
        arguments: ['@doctrine.orm.entity_manager']
    domain_site.manager.geolocation:
        class: Domain\SiteBundle\Manager\GeolocationManager
        arguments: ['@doctrine.orm.entity_manager']
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager, {facebook: facebookId, google: googleId}]
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]