services:
    oxa.user.authentication_handler:
        class:        Oxa\Sonata\UserBundle\Handler\AuthenticationHandler
        arguments:    [@router, @security.context, @fos_user.user_manager, @service_container]