services:
    #hwioauth user provider
    oxa.user.oauth_provider:
        class: Oxa\Sonata\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments: [@fos_user.user_manager, {facebook: facebookId, google: googleId}]
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

    #handlers section
    oxa.user.authentication_handler:
        class:        Oxa\Sonata\UserBundle\Handler\AuthenticationHandler
        arguments:    ['@translator']

    #repository section
    oxa.repository.group:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Oxa\Sonata\UserBundle\Entity\Group

    #managers section
    oxa.manager.groups:
        class: Oxa\Sonata\UserBundle\Manager\GroupsManager
        arguments: ['@oxa.repository.group']