<?php

namespace Domain\BannerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Oxa\GeolocationBundle\Model\Geolocation\LocationValueObject;

use Domain\BusinessBundle\Entity\BusinessProfile;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchRepository extends EntityRepository
{
    protected function getSearchQueryBuilder()
    {
        return $this->createQueryBuilder('bp')
            ->from('BusinessProfile', 'bp')
            ->where('b.isActive = true');
    }

    protected function getSearchQueryBuilderWithBoundaries()
    {
        return $this->getSearchQueryBuilder()
            ->join('bp.categories', 'bp_c')
            ->join('bp.areas', 'bp_a')
            ->join('bp.tags', 'bp_t')
            ->join('bp.brands', 'bp_b')
            ->join('bp.businessReviews', 'bp_r');
    }

    protected function getSearchQueryBuilderWithCaterogy()
    {
    }

    protected function getSearchQuery()
    {
        $this->getEntityManager();
        //$this->getDoctrine()->getManager();
    }

    public function searchByPhraseAndLocation(sting $phrase, LocationValueObject $locationName)
    {

    }
}
