services:

    oxa.service.http_client:
        class: GuzzleHttp\Client

    oxa.service.wistia_api_client:
        class: Oxa\WistiaBundle\Service\WistiaAPIClient
        arguments: ['@oxa.service.http_client']

    oxa.manager.wistia_projects:
        class: Oxa\WistiaBundle\Manager\WistiaProjectManager
        arguments: ['@oxa.service.wistia_api_client']

    oxa.manager.wistia_medias:
        class: Oxa\WistiaBundle\Manager\WistiaMediaManager
        arguments: ['@oxa.service.wistia_api_client']

    oxa.manager.wistia:
        class: Oxa\WistiaBundle\Manager\WistiaManager
        arguments: ['@oxa.manager.wistia_projects', '@oxa.manager.wistia_medias']