<?php

namespace Domain\ArticleBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    protected function getArticlesQueryBuilder()
    {
        return $this->createQueryBuilder('a')
            ->where('a.isPublished = true');
    }

    protected function getArticlesForHomepageQueryBuilder()
    {
        return $this->getArticlesQueryBuilder()
            ->andWhere('a.isOnHomepage = true')
            ->addOrderBy('a.createdAt', "DESC");
    }

    public function getArticlesForHomepage($limit)
    {
        return $this->getArticlesForHomepageQueryBuilder()
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
