services:
    sonata.user.admin.user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin
        arguments: [~, %sonata.user.admin.user.entity%, %sonata.user.admin.user.controller%]
        tags:
            - {name: sonata.admin, show_in_dashboard: true, manager_type: orm, label: Users}

    sonata.user.admin.group:
        class: Application\Sonata\UserBundle\Admin\GroupAdmin
        arguments: [~, %sonata.user.admin.group.entity%, %sonata.user.admin.group.controller%]
        tags:
        - { name: sonata.admin, manager_type: orm, show_in_dashboard: true, label: Groups }

