services:
    oxa_config:
        class: Oxa\ConfigBundle\Service\Config
        arguments: ["@doctrine.orm.entity_manager"]
    oxa_config.twig.extension:
        class: Oxa\ConfigBundle\Twig\Extension\ConfigExtension
        arguments: ["@oxa_config"]
        tags:
             - { name: 'twig.extension' }